Balloon/sys/Device.c, buildAll.bat, packaging/buildall.bat
This is part of the effort to merge the stable branch (where Fedora and RHEL virtio-win drivers come from) into master.
The first patch fixes a bad merge in https://github.com/virtio-win/kvm-guest-drivers-windows/pull/104 and the second one adds /packaging to the build.
=> Merge stable to master: the last pieces

NetKVM/Common/ParaNdis-Common.cpp
This series solves the issue with illegal vlan id (and other configurations) by fixing the current debug print to be printed. More explanation can be found in the patches.
=> BZ#1256626

Tools/pushpdb.cmd
If the store is not accessible the script should not get stuck
in an inifinite loop trying to create the lock file. This commit
adds another check which aborts the pushpdb attempt in such a
case.
Also fixing 'timeout' invocation to make sure it runs the Windows
tool and not the GNU one when running under Cygwin.
=> pushpdb: Don't loop indefinitely if symbol store is broken

NetKVM/Common/ParaNdis-Common.cpp
Signed-off-by: Sameeh Jubran <sjubran@redhat.com>
=> NetKVM: MTU Report: Fix mtu offset

.appveyor.yml, README.md, Tools/build.bat, buildAll.bat
This pull request introduces integration with Appveyor CI.
On each push and PR (including this one) the code will be build on Appveyor, build state notifications will be sent to virt-win-devel@redhat.com.
=> Integration with Appveyor CI

NetKVM/NetKVM-VS2015.vcxproj, viorng/VirtRNG Package/VirtRNG Package.vcxproj
netkvmco.pdb
viorngci.pdb
viorngum.pdb
were not getting packaged so they never made it into neither the raw build nor the .iso.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1457845
=> Publish missing pdbs to the Install directory

VirtIO/VirtIOPCICommon.c
=> cosmetic changes - use WDK defines for PCI BAR manipulations

vioscsi/helper.h, vioscsi/resources.h, vioscsi/vioscsi.c, vioscsi/vioscsi.h
The first step toward providing better wmi support in vioscsi driver. This serial is mostly focused on building proper MS_SM_AdapterInformationQuery and MS_SM_PortInformationMethods WMI handlers.
The following PS script should be helpful for testing the new capabilities 
$SCRIPT_NAME = "VioScsiWMI"
$DefaultPortCountPerAdapter = 1
$PortIndex =  0
Write-Host "$SCRIPT_NAME - Starting Execution Virtio SCSI WMI Testing Powershell Script"
$adaptersColl = Get-WmiObject -namespace "root\wmi" -Class MS_SM_AdapterInformationQuery
$ms_smhba_fc_port 
if($adaptersColl -ne $null)
{
foreach ($AdapterInfo in $adaptersColl) 
{
$InstanceName = $AdapterInfo.InstanceName  
Write-Host "==========================================================="
Write-Host "UniqueAdapterId             " …
=> better vioscsi support for MS_SM_AdapterInformationQuery and MS_SM_PortInformationMethods classes

Balloon/app/main.cpp, Balloon/app/memstat.cpp, Balloon/app/service.cpp, Balloon/app/utils.cpp, Balloon/app/utils.h, Balloon/sys/Device.c, Balloon/sys/ProtoTypes.h
A bunch of minor tweaks to make static analysis happy and a few actual bug fixes, mostly around error handling.
=> balloon: Static analysis fixes and tweaks

vioserial/app/device.cpp, vioserial/app/main.cpp, vioserial/sys/Driver.c, vioserial/sys/Port.c, vioserial/sys/vioser.h
Minor tweaks to make static analysis happy.
=> vioserial: Static analysis fixes and tweaks

NetKVM/Common/ParaNdis-Common.cpp
Check https://bugzilla.redhat.com/show_bug.cgi?id=1351089 for more details.
=> netkvm: BZ#1351089: Fixing MAC address configuration in virtio 1.0 device

NetKVM/Documentation/Tracing.md, Tools/getpdbinfo.bat
WPP tracing documentation update, with the tool described and used added.
=> WPP Tracing documentation for NetKVM

NetKVM/Common/Trace.h
=> NetKVM: WPP: Include function name in Dprintf

vioscsi/helper.c, vioscsi/helper.h, vioscsi/vioscsi.c, vioscsi/vioscsi.h
This patch should fix the following issue
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/251
Questions about the device queue depth for vioscsi and viostor
Hopefuly without regression to Bug 1013443 - Win7-64 guest installation
with virtio-scsi BSOD
=> [vioscsi] Increasing the size of queue depth.

vioscsi/vioscsi.c
Win7/win2008 guest BSOD after the first reboot when installing os with virtio_scsi
https://bugzilla.redhat.com/show_bug.cgi?id=1568739
=> [vioscsi]. Fix for  Bug 1568739 

NetKVM/wlh/ParaNdis6-Driver.cpp
=> NetKVM: Log interrupt vector to CPU mapping

viostor/virtio_stor.c
Bug 1428641 Windows guest physical block size change to 512 after installation with the size 4096
=> [viostor] Fix for Bug 1428641. Report READ_CAPACITY16_DATA::LogicalPerPhysicalExponent

NetKVM/wlh/ParaNdis6-Impl.cpp
When the driver receives GRO coalesced packet from the device
it provides number of coalesced segments to the OS.
The estimation was not correct:
There was an assumption that segments always have MTU size,
when this happens only by default. Certification tests and
networking tools can control that (example is -M option of iperf)
Even in this case the calculation was wrong, it did not take
in account that default MSS is smaller than default MTU.
Current commit corrects the calculation.
=> netkvm: Calculate number of coalesced segments correctly

NetKVM/Common/ParaNdis-CX.cpp
Windows with NetKVM has a little chance hang during shutdown.
If the NetKVM has not initialized yet (or reset), QEMU will ignore
the control message. It will cause driver hanging in infinite while loop
for waiting response (which leads to windows hang in shutdown). In our
test, there is a little chance to receive an OID for setting multicast list
after device reset. To make symptom more clear, I have added some log.
Below is the log and call stack when this situation happens:
Logs:
[ParaNdis_OnShutdown]=>
Common [ParaNdis_ResetVirtIONetDevice] Done
[ParaNdis_OnOidSetMulticastList] Go
[ParaNdis_UpdateDeviceFilters] Do
[CParaNdisCX::SendControlMessage] enter: 4277 - cls: 0, cmd: 0
CParaNdisCX::SendControlMessage - ERROR: in while
Assertion: *** DPC watchdog timeout
This is NOT a break in …
=> NetKVM: Prevent hanging in SendControlMessage

Tools/Driver.Vendor.props
=> build: Add VerArch property for ARM64

Balloon/app/service.cpp
Unregister device notification is not allowed within the event
handler. Although the unregistering was done in a different thread,
it seems that waiting for the thread termination blocks the event
handler function. That caused a service crash in Windows 10 and a
failure to release the device handle in Windows 2019.
Solved by moving the unregister function call to a work object.
=> balloon: bz#1546821: device hot-unplug fails when service is running

NetKVM/wlh/ParaNdis6-RSS.cpp
In case of RSS disable IOCTL the driver rejects the
command due to 'invalid length' although the length of
of the received structure is correct. The structure does
not include any extensions as they are not required for
case of RSS disable. Current commit moves checks that
expect extended length of received structure to the
case when the IOCTL does not disable RSS. It also adds
printouts for each case the driver fails the IOCTL due
to wrong length.
For example, such IOCTL comes during driver disable.
=> netkvm: fix IOCTL processing of RSS disable

vioscsi/vioscsi.vcxproj
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1691209#c2
=> add custom build step to deal with dvl.xml file

vioinput/sys/HidMouse.c
https://bugzilla.redhat.com/show_bug.cgi?id=1588425
The mentioned commit fixes the problem it was intended to fix
but contains 2 mistakes. The purpose of said commit was to allow
some relative non-XY axes (expecially REL_WHEEL) to be used with
absolute pointing devices (i.e. ABS_XY+REL_WHEEL).
Problem1: in case of combined device (ABS_XY+REL_XY+REL_WHEEL)
the change in the code causes absolute and relative axes to be
exposed in the same mouse device.
Windows HID stack rejects such devices, so the rule is to expose
absolute ABS_XY only if REL_XY are not present (as described in
commit 52e521d2e9). The mistake was in use of InputCfgDataHasBit
after DecodeNextBit on the same structure (DecodeNextBit clears
bits of interest in the bitmap and later InputCfgDataHasBit returns
unexpected …
=> vioinput: Fix mistakes in commit 4c9942754912

NetKVM/CoInstaller/RegParam.cpp
Signed-off-by: Michał Janiszewski <janisozaur@gmail.com>
=> netkvm: Plug memory leak on exception

viorng/VirtRNG Package/VirtRNG Package.vcxproj, viorng/VirtRNG Package/viorng_pack.props
=> viorng: fix vendor info substitution

Tools/Trace/vioscsi.bat, vioscsi/helper.c, vioscsi/vioscsi.c, vioscsi/vioscsi.h
Bug 1787022 - Windows virtio-scsi driver performs poorly when reading/writing big data blocks
=> vioscsi performance improvment.

Balloon/sys/Device.c
https://bugzilla.redhat.com/show_bug.cgi?id=1788042
Fix synchronization of EvtFileClose and ReleaseHardware.
Access memory allocated by WDF Virtio DMA API only when
it is safe.
=> balloon: synchronize ReleaseHardware with EvtFileClose

Tools/Trace/vioscsi.bat, vioscsi/helper.c, vioscsi/vioscsi.c, vioscsi/vioscsi.h
[vioscsi] fix for bz#1791147 BSOD when running Bus Reset Test
=> Vioscsi perf

viostor/virtio_stor.c, viostor/virtio_stor_hw_helper.c, viostor/virtio_stor_hw_helper.h
bugfix for BZ#1821560 - viostor driver does not return correct serial number length.
=> bugfix for BZ#1821560

viofs/svc/virtiofs.c
Replaced %Iu format specification with %I64u so 64-bits values are
formatted correctly on a 32-bit platform.
=> viofs-svc: bz#1865823: fix a crash on Windows 8 (32-bits)

viostor/virtio_stor.c, viostor/virtio_stor.h
=> [viostor] some performance parameters tweaking

viosock/sys/viosock.inx, viosock/sys/viosock_wow.inx
Signed-off-by: Basil Salman <basil@daynix.com>
=> viosock: Add modern HW ID to viosock inf

Tools/Driver.Common.targets
Will be used by NETKVM for INF file generation.
This commit formally will cause to request running HCK on all the projects.
Note that it does not change anything in any specific project.
=> build: define custom target "GenerateInf"

viofs/svc/virtiofs.c
Replaced the empty directory check (that apparently was current only
for tmpfs) with a readdir request and then count the files.
=> viofs-svc: bz#1873911: unable to delete empty directory

viofs/svc/virtiofs.c
If FUSE_FALLOCATE is called passing a length of 0 it returns an error.
Since allocating 0 bytes is expected to just do nothing, it is better to prevent the call to FUSE_FALLOCATE and report a success instead.
This should fix the issue when creating new files from Windows Explorer.
Signed-off-by: Tex Killer Tex.Killer@hotmail.com
=> viofs-svc: Fix issue with allocating 0 bytes

contributing.md
Adding contributing.md with contribution guidelines
Signed-off-by: Yan Vugenfirer <yan@daynix.com>
=> Add contribution guidelines to the project

Balloon/sys/Device.c
=> balloon: add PAGED_CODE for SDV

viofs/svc/virtiofs.c
=> viofs-svc: change service main function to accept session change events

viogpu/common/bitops.cpp, viogpu/common/helper.h, viogpu/common/viogpu_idr.cpp, viogpu/common/viogpu_pci.cpp, viogpu/common/viogpu_queue.cpp, viogpu/viogpudo/driver.cpp, viogpu/viogpudo/trace.h, viogpu/viogpudo/viogpudo.cpp, viogpu/viogpudo/viogpudo.vcxproj, viogpu/viogpudo/viogpudo.vcxproj.filters
=> [viogpudod] WPP tracing for virtio-gpu dod driver

vioscsi/vioscsi.c
When MSIs are disabled, the OS uses INTx and calls VioScsiInterrupt to
handle interrupts. This ISR eventually calls CompleteRequest on DIRQL.
Sometimes StorPortFreeContiguousMemorySpecifyCache is called during
request completion, but it requires IRQL <= DPC_LEVEL, not DIRQL.
Sometimes it leads to deadlock. It is necessary to complete requests in
IsrDpc, like VioScsiMSInterrupt does.
=> vioscsi: move request handler from INTx ISR to DPC

viogpu/viogpudo/viogpudo.cpp, viogpu/viogpudo/viogpudo.h
=> [viogpu-dod] small changes in Registry related code

viofs/svc/fusereq.h, viofs/svc/virtiofs.c
Issue: https://issues.redhat.com/browse/RHELPLAN-64368
=> Add a support for symblic links

viofs/pci/viofs.inf
=> viofs-pci: rhbz#1913664: fix device's subsystem value

NetKVM/Common/ParaNdis_Protocol.cpp
https://bugzilla.redhat.com/show_bug.cgi?id=1925916
Currently the notify object prevents binding of vioprot
to virtio adapter only at installation time and only
due to the fact that virtio adapter is not in the list
of supported adapter. It is still possible to enable
this binding manually and this will cause infinite
recursion of oids or sent packets.
Add detection of such case and prevent the binding.
=> netkvm: reject binding attempt to netkvm

viogpu/common/viogpu_pci.cpp
=> [viogpu] Fix HyperVisor Code Integrity Readiness Test problem

viosock/sys/Device.c, viosock/sys/Driver.c, viosock/sys/Evt.c, viosock/sys/IsrDpc.c, viosock/sys/Loopback.c, viosock/sys/Rx.c, viosock/sys/Socket.c, viosock/sys/Tx.c, viosock/sys/utils.c, viosock/sys/viosock.h, viosock/vioconnect.py, viosock/violisten.py, viosock/viosocklib-test/viosocklib-test.c
See patch comments for details
=> Viosock: small improvements and bugfixes

NetKVM/Common/ParaNdis_Common.cpp, NetKVM/Common/ParaNdis_Protocol.cpp, NetKVM/Common/ParaNdis_RX.cpp, NetKVM/Common/ParaNdis_TX.cpp, NetKVM/Common/ndis56common.h, NetKVM/Common/netkvm.mof, NetKVM/DebugTools/WMI/netkvm-wmi.cmd, NetKVM/NotifyObject/Readme.md, NetKVM/NotifyObject/netkvmno.cpp, NetKVM/NotifyObject/vioprot.inf, NetKVM/ProtocolService/CProcessRunner.h, NetKVM/ProtocolService/ProtocolService.cpp, NetKVM/ProtocolService/ProtocolService.vcxproj, NetKVM/ProtocolService/ProtocolService.vcxproj.filters, NetKVM/ProtocolService/Service.h, NetKVM/ProtocolService/guid.cpp, NetKVM/ProtocolService/stdafx.h, NetKVM/ProtocolService/uninstall.cpp, NetKVM/wlh/ParaNdis6_Driver.cpp, NetKVM/wlh/ParaNdis6_Impl.cpp, NetKVM/wlh/ParaNdis6_Oid.cpp, NetKVM/wlh/ParaNdis6_RSS.cpp
Mainly failover change: the NETKVM indicates link only after the VIOPROT was bound to the respective VF adapter.
=> Standby/failover feature + other small fixes

viofs/svc/virtiofs.c
=> viofs-svc: rhbz#1925144: add support symbolic links to directories

viofs/svc/fusereq.h, viofs/svc/virtiofs.c
=> viofs-svc: rhbz#1978122: fix rename when shared folder is a nfs mount

viogpu/common/viogpu.h, viogpu/viogpudo/viogpudo.cpp
=> [viogpudo] extending edid related data

viorng/viorng/read.c
=> viorng: Fix SDV EvtIoStopCancel issue

Balloon/sys/balloon.vcxproj, pvpanic/pvpanic/pvpanic.vcxproj, viocrypt/sys/viocrypt.vcxproj, viofs/pci/viofs.vcxproj, viogpu/viogpudo/viogpudo.vcxproj, vioinput/sys/vioinput.vcxproj, viorng/viorng/viorng.vcxproj, vioserial/sys/vioser.vcxproj, viosock/sys/viosock.vcxproj
=> build: Copy DVL to install dir

Balloon/sys/balloon.vcxproj, fwcfg64/fwcfg.props, fwcfg64/fwcfg.vcxproj, ivshmem/ivshmem.vcxproj, pvpanic/pvpanic/pvpanic.props, pvpanic/pvpanic/pvpanic.vcxproj, viocrypt/sys/viocrypt.vcxproj, viocrypt/viocrypt_pack.props, viofs/pci/viofs.props, viofs/pci/viofs.vcxproj, viogpu/viogpudo/viogpudo.vcxproj, vioinput/sys/vioinput.vcxproj, viorng/viorng/viorng.props, viorng/viorng/viorng.vcxproj, vioserial/sys/vioser.vcxproj, viosock/sys/viosock.props, viosock/sys/viosock.vcxproj
=> build: Copy DVL to solution install dir

buildAll.bat
=> buildAll: Add vioinput SDV target

vioinput/sys/HidConsumer.c, vioinput/sys/HidJoystick.c, vioinput/sys/HidKeyboard.c
=> vioinput: Fix arithmetic overflow (C26451) warnings

viosock/cleanAll.bat, viosock/sys/Device.c, viosock/sys/Evt.c, viosock/sys/Loopback.c, viosock/sys/Rx.c, viosock/sys/Socket.c, viosock/sys/Tx.c, viosock/sys/public.h, viosock/sys/viosock.h, viosock/viosock.sln, viosock/wsk/cleanAll.bat, viosock/wsk/precomp.h, viosock/wsk/provider.c, viosock/wsk/socket.c, viosock/wsk/viowsk.c, viosock/wsk/viowsk.h, viosock/wsk/wsk.vcxproj, viosock/wsk/wsk.vcxproj.filters
+ code defects eliminated
+ WSK interface initial commit
=> Viosock: Tx and Rx paths refactoring

fwcfg64/fwcfg.props
=> fwcfg64: Fix install dir location

buildAll.bat, vioinput/buildAll.bat, vioinput/hidpassthrough/hidpassthrough.props, vioinput/hidpassthrough/hidpassthrough.vcxproj
=> Build DLV for vioinput\hidpassthrough

Tools/build.bat
=> build: Run CodeQL automatically if binary present

viofs/svc/virtiofs.cpp
VirtIO-FS service can get `DebugFlags` (DWORD), `DebugLogFile` (String), `MountPoint` (String) from `HKLM\Software\VirtIO-FS` as depicted below:
=> VirtIO-FS: RHBZ#1918312: add parameters parsing from registry when cmdline arguments are absent

ivshmem/ivshmem.props
=> ivshmem: Remove code for legacy OSes

pvpanic/pvpanic/pvpanic.vcxproj
=> pvpanic: Remove code for legacy OSes

vioinput/sys/Driver.c, vioinput/sys/vioinput.props
=> vioinput: Remove code for legacy OSes

Q35/buildAll.bat
=> q35: Remove code for legacy OSes

pciserial/buildAll.bat
=> pciserial: Remove code for legacy OSes

viosock/lib/trace.h, viosock/sys/Driver.c, viosock/sys/trace.h
=> viosock: Remove code for legacy OSes

viostor/viostor.vcxproj
=> viostor: Remove code for legacy OSes

vioserial/sys/Driver.c, vioserial/sys/trace.h, vioserial/sys/vioser.vcxproj
=> vioserial: Remove code for legacy OSes

viocrypt/dll/viocrypt-prov.vcxproj, viocrypt/package/package.vcxproj, viocrypt/sys/WppTrace.h, viocrypt/sys/viocrypt.vcxproj, viocrypt/test/viocrypt-test.vcxproj
=> viocrypt: Remove code for legacy OSes

Balloon/sys/Driver.c, Balloon/sys/balloon.vcxproj, Balloon/sys/trace.h
=> Balloon: Remove code for legacy OSes

vioscsi/trace.h, vioscsi/vioscsi.props, vioscsi/vioscsi.vcxproj
=> vioscsi: Remove code for legacy OSes

viofs/pci/viofs.c, viofs/pci/viofs.vcxproj
=> viofs: Remove code for legacy OSes

viorng/viorng/viorng.vcxproj
=> viorng: Remove code for legacy OSes

viogpu/viogpuap/viogpuap.props, viogpu/viogpudo/viogpudo.props, viogpu/viogpusc/viogpusc.props
=> viogpu: Remove code for legacy OSes

fwcfg/buildAll.bat
=> fwcfg: Remove code for legacy OSes

VirtIO/VirtioLib.vcxproj, VirtIO/WDF/MemPortIO.c, VirtIO/WDF/VirtioLib-WDF.vcxproj
=> VirtIO: Remove code for legacy OSes

NetKVM/Common/ParaNdis_TX.cpp
https://bugzilla.redhat.com/show_bug.cgi?id=1972487
Complete packets (i.e. get buffers from TX queue and
process waiting list) only when called from DPC (on
TX completion DPC or RX DPC). According to the tests
thos solves assertion "pCurrentNetBufferList" in the
NDPROT630 driver.
=> netkvm: do not complete packets in sending path

viogpu/common/bitops.cpp, viogpu/common/bitops.h, viogpu/common/viogpu.h, viogpu/viogpudo/viogpudo.cpp
bugfix for BZ#1965159 Reboot/shutdown/Reset failed and hit black screen after installing viogpudo driver on win2012-64
=> [viogpudo] patch edid data returned by qemu 

.github/CODEOWNERS
@YanVugenfirer 
Please check these errors:
```
Unknown owner on line 8: make sure @viktor-prutyanov exists and has write access to the repository
/fwcfg64/           @viktor-prutyanov @YanVugenfirer
Unknown owner on line 13: make sure @viktor-prutyanov exists and has write access to the repository
/pvpanic/           @viktor-prutyanov @YanVugenfirer
Unknown owner on line 15: make sure @kostyanf14 exists and has write access to the repository
/Tools/             @kostyanf14 @YanVugenfirer
Unknown owner on line 17: make sure @viktor-prutyanov exists and has write access to the repository
/viofs/             @viktor-prutyanov @YanVugenfirer
Unknown owner on line 23: make sure @irudakov77 exists and has write access to the repository
/viosock/           @irudakov77 @YanVugenfirer
```
=> Add code owners config

viofs/pci/ioctl.c
=> viofs: Remove extra annotation and return to fix SDV build

viofs/svc/virtiofs.cpp
For virtio-fs to work with an Active Directory connected system, we can't use NetUserGetInfo.
Instead, use WTSQueryUserToken to get a token for the security context of the logged-in user,
and then query the user and group SID. Use the SID to get the UID using WinFSP's
preexisting mapping, which for standard users is just the previously used 0x30000+RID.
Signed-off-by: Daniel Trevitz <daniel.trevitz@wika.com>
=> Add Active Directory support

vioscsi/vioscsi.c
Reported-by : main@ehvag.de
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/809
=> [vioscsi] fix for BZ#2118630 saving BSOD crash dumps fails

viorng/LICENSE, viorng/cng/um/LICENSE, viorng/coinstaller/LICENSE, viorng/test/LICENSE, viorng/viorng/LICENSE
=> virtio-rng: BZ#2120249 - Add LICENSE file to virtio-rng project

ivshmem/LICENSE, ivshmem/test/LICENSE
Comment for PR: no BZ number in commit message because ivshmem is not distributed downstream
=> ivshmem: Add license files

viofs/pci/ioctl.c
=> viofs: Check ActionFlags before request unmark

Balloon/sys/queue.c
=> Balloon: Check ActionFlags before request unmark

vioserial/sys/Port.c
=> vioser: Check ActionFlags before request unmark

.github/labeler.yml, .github/workflows/labeler.yml
Issue Labeler automatically adds/removes labels for issues based on its title and content.
=> Add 'Issue Labeler' GitHub Action

viofs/svc/utils.h, viofs/svc/virtiofs.cpp
Previously, parent node-id for FUSE_SYMLINK was set to target's parent, which is wrong. Set parent to linkname's parent.
Also, allow relative target paths only to prevent paths outside of VirtIO-FS from being target paths.
Additionally, move some code from device-related part to separate file without change of logic.
=> RHBZ#1999409: VirtIO-FS: fix parent and forbid absolute target path in SetReparsePoint

Tools/Driver.Platform.props
Fixes for https://bugzilla.redhat.com/show_bug.cgi?id=2138115
=> Add auto detect for VisualStudioToolset v143

pvpanic/pvpanic/pvpanic.c
=> [pvpanic] bug fix for BZ#2139663 - Setting Enable/Disable is not avalable on driver Pvpanic

viofs/svc/virtiofs.cpp
The host daemon may be running inside the Linux user namespace, so unmapped UIDs and GIDs are shown as `nobody` (65534). Files/directories must not be created with this ID, so the service should try to preserve a valid ID number if shared directory owner turns out to be `nobody`.
=> RHBZ#2142718: VirtIO-FS: fix 'nobody' shared root owner handling

vioscsi/vioscsi.c
This PR is to change implementation of VioScsiReadRegistryPhysicalBreaks to make it read a passed parameter instead of hardcoded one. If we need to add more parameters via registry, it will help us avoid bloat of the code with multiple functions to read various registry values. 
HLK2022 and HCK (Windows 2012R2) passed all tests as expected (without new failures). Build was done using EWDK2022.
=> vioscsi: Add more robust routine to read registry parameters

viofs/svc/virtiofs.cpp
While the service waits in `SvcStart` on `EvtDeviceFound` it can't set `SERVICE_ACCEPT_STOP`, so the service is unstoppable until no device found. So, remove this waiting and return success if there is no device yet. `DeviceInterfaceArrival` does all the work anyway.
=> RHBZ#2156678: VirtIO-FS: remove EvtDeviceFound and wait in SvcStart

NetKVM/Common/ParaNdis_Common.cpp, NetKVM/netkvm-base.txt
test patches to check if RxCapacity changes pass HCK-CI
=> netkvm: RxCapacity changes

vioinput/package/package.vcxproj
Check generated INF before merge
=> Fix vendor prefix generation in vioinput package

viofs/svc/virtiofs.cpp
Windows has a restriction that the filesystem name must be "NTFS" to run program with admin privilege from it.
Add -F option and allow viofs to masquerade itself as any filesystem (e.g. NTFS) so the Windows restriction is lifted and we may run lots of useful tools and perform software installs from it.
WinFsp's devels are aware of it and in their example memfs they did it this way. The following is an excerpt from their FAQ.
https://winfsp.dev/doc/Frequently-Asked-Questions/
2. I cannot run a program located in a WinFsp drive as administrator. I cannot run regedit.exe from within a WinFsp drive.
When running an executable as administrator, the Windows OS seems to require that the name of the file system that is housing the executable is "NTFS". For example, the MEMFS file system with the …
=> viofs: add -F option

vioscsi/helper.c, vioscsi/vioscsi.c, vioscsi/vioscsi.inx
https://issues.redhat.com/browse/RHEL-465 - vioscs part
=> [Vioscsi] Fix multi-queue support in case if number of CPUs is not matching number on virtual queues

viosock/sys/Rx.c
The RxPktList must be processed in time, or it is very easy to stuck both the Server sending side and  the Windows Client recving side. Think about the following scenario:
1) the host server(with CID 2) side continuously send data; 
2) the VM windows client side continuously receive data; 
3) the server side sent 128(ring num) rw packets, and the client side receives 128(ring num) rw packets, then each packet enqueues one Cb and returns it's buffer;
4) then, the client side postpone all 128 packet to RxPktList, since it can not find free buffers(VIOSockRxCbPop return NULL), meanwhile the host send side can not send any data any more;
5) one client side read thread reads all the 128 packet data, without process the RxPktList;
till now, the client side will not be able to receive data any …
=> viosock: fix the recving stuck issue

viosock/sys/Rx.c
Like the previous PR #953, we should also process the RxPktList in VIOSockReadCleanupCb , otherwise the same stuck issue may occur after the process terminated, when all buffers in RxCbList return to RxCbBuffers in VIOSockReadCleanupCb.
=> viosock: fix recv stuck after process terminated

viogpu/viogpudo/viogpudo.cpp
During its DxgkDdiStartDevice routine, the viogpudo driver is provided with an DXGKRNL_INTERFACE structure containing mostly pointers to various WDDM interface functions that it may need to use. The driver copies this structure to its device-specific block of memory. However, the driver expected the system would provide the same version of the structure it uses, however, this is not necessarily true. Such behavior resulted in copying memory past the end of the system-provided structure which triggered the crash.
Fixed version of the driver copies only bytes really occupied by the DXGKRNL_INTERFACE structure (stored in its Size member).
I initially noticed this problem with `qxldod` (https://gitlab.freedesktop.org/spice/win32/qxl-wddm-dod/-/merge_requests/2) but `viogpu` uses the same code …
=> viogpu: Correctly copy the DXGKRNL_INTERFACE structure

viostor/virtio_stor.c
Signed-off-by:  Zhang JianMing <zhangjianming.zjm@alibaba-inc.com>
for the problem description
please visit #829
=> [viostor] add protection against IO out-of-bounds access

NetKVM/wlh/ParaNdis6_Driver.cpp
Signed-off-by:  Zhang JianMing <zhangjianming.zjm@alibaba-inc.com>
for the problem description
please visit virtio-win#1002
=> [netkvm] add surprise remove attribute

viogpu/viogpudo/viogpudo.cpp
related to https://issues.redhat.com/browse/RHEL-21032 and https://issues.redhat.com/browse/RHEL-1292
=> [viogpudod] report resolution 1024x768 as the preferred one

vioscsi/helper.c, vioscsi/helper.h, vioscsi/vioscsi.c, vioscsi/vioscsi.h, vioscsi/vioscsi.mof, vioscsi/vioscsidt.h
https://issues.redhat.com/browse/RHEL-19188
=> [vioscsi] add support for tracing SRB processing time 

NetKVM/CoInstaller/netkvmco-vs2015.vcxproj, NetKVM/Common/ParaNdis-Util.h, NetKVM/Common/ParaNdis_LockFreeQueue.h, NetKVM/Common/ParaNdis_TX.cpp, NetKVM/netkvm-base.txt, NetKVM/wlh/ParaNdis6_RSS.cpp
https://issues.redhat.com/browse/RHEL-19430
=> Rx queue size adaptive (up to 1024) + minor fixes

viosock/wsk/wsk-utils.c
Buffers for WskSend/WskReceive calls are represented by WSK_BUF structures as memory descriptor lists (MDLs). Since the caller is responsible for making them fully initialized, there is no need to use `MmProbeAndLockPages` to lock the buffer memory in place (`IoBuildAsynchronousFsdRequest` does that under the hood). Since, the Socket Driver device object works in so-called direct mode, we just need to copy buffer MDLs through `IoBuildPartialMdl` and pass these copies to the Socket Driver within corresponding `IRP_MJ_READ/IRP_MJ_WRITE` IRPs. Such approach simplifies the code and also makes `WskSend/WskReceive` usable at IRQL = `DISPATCH_LEVEL` (which they should be from the beginning).
=> WSK: Simplify and fix WskSend/WskReceive

viogpu/viogpudo/viogpudo.inx
Resolve: https://issues.redhat.com/browse/RHEL-26213
=> viogpudo: Enforce driver isolation in INF files

NetKVM/netkvm-base.txt
Resolve: https://issues.redhat.com/browse/RHEL-26207
=> NetKVM: Enforce driver isolation in INF files

viogpu/common/bitops.cpp, viogpu/common/viogpu_queue.cpp, viogpu/viogpudo/viogpudo.cpp, viogpu/viogpudo/viogpudo.h
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/1057 
https://issues.redhat.com/browse/RHEL-30199
=> fix BSOD screen doesn't show up with VirtIO VGA problem 

Tools/Driver.Common.props
ballon.inf example of usage:
```
;/*++
;
;INX_COPYRIGHT_1
;INX_COPYRIGHT_2
;
;Module Name:
;    BALLOON.INF
;
;Abstract:
;
;Installation Notes: 
;    Step by step driver installation wiki:
;        https://github.com/virtio-win/kvm-guest-drivers-windows/wiki/Driver-installation
;
;--*/
[Version]
Signature="$WINDOWS NT$"
Class=System
ClassGuid={4d36e97d-e325-11ce-bfc1-08002be10318}
Provider=%VENDOR%
DriverVer=01/01/2008,0.0.0.1 ; this line will be replaced with stampinf
CatalogFile=Balloon.cat
DriverPackageType = PlugAndPlay
DriverPackageDisplayName = %BALLOON.DeviceDesc%
PnpLockdown = 1
[DestinationDirs]
DefaultDestDir = INX_PLATFORM_DRIVERS_DIR
[SourceDisksNames]
1 = %DiskId1%,,,""
[SourceDisksFiles]
balloon.sys  = 1,,
;*****************************************
; BALLOON  Install Section …
```
=> CI NO BUILD: Add INX_* replacements for drivers dir

NetKVM/Common/ndis56common.h, NetKVM/wlh/ParaNdis6_RSS.cpp, NetKVM/wlh/ParaNdis_Poll.cpp
https://issues.redhat.com/browse/RHEL-33334
Fix wrong affinity assignment.
=> netkvm: fix affinity of poll handlers

viogpu/common/viogpu_queue.cpp, viogpu/viogpudo/viogpudo.cpp
https://issues.redhat.com/browse/RHEL-30199
=> make enable system display path non-paged. 

VirtIO/WDF/Dma.c, VirtIO/WDF/VirtIOWdf.h, VirtIO/WDF/private.h
Prerequisite for https://issues.redhat.com/browse/RHEL-11405 Added device-to-host transactions API.
=> virtio-wdf: extend DMA API to support also RX transfer

viomem/sys/viomem.c
=> https://issues.redhat.com/browse/RHEL-30694 - Improve waiting for command submissions.

Balloon/sys/balloon.inx
https://issues.redhat.com/browse/RHEL-58239
Set DMAR compatibility as 2 (if driver verifier enabled)
=> balloon: Update INF to support DMA remapping

viomem/sys/viomem.c
Comments explaining VIRTIO_MEM_F_UNPLUGGED_INACCESSIBLE feature and added some cosmetic changes.
=> [viomem][https://issues.redhat.com/browse/RHEL-30692]  VIRTIO_MEM_F_UNPLUGGED_INACCESSIBLE feature

.hck-ci/triggers.yml
Merge after https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1166 and https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1167
=> [CI-NO-BUILD] Update HCK-CI triggers

viomem/sys/viomem.c
PR created after applying changes after code review:
- removed the old definition of the function, which was kept in the source 
file surrounded with #if #else #end)
- added a sanity check to limit the number of blocks that can be processed 
(member virtio_mem_req_state::nb_blocks is a type of DWORD, so the limit is 
up to 65535 blocks); if the number of blocks is greater than 65535, the function fails)
=> [viomem][https://issues.redhat.com/browse/RHEL-31880] Optimized STATE request processing.

viostor/viostor.inx
https://issues.redhat.com/browse/RHEL-58679
https://issues.redhat.com/browse/RHEL-62318
Disable DMAR for storage devices for now.
=> viostor: disable DMAR in the INF file

contributing.md
Jira: https://issues.redhat.com/browse/RHEL-65784
=> RHEL-65784: Update code style section in contributing.md [CI-NO-BUILD]

viogpu/common/viogpu_idr.cpp, viogpu/common/viogpu_idr.h, viogpu/common/viogpu_pci.cpp, viogpu/common/viogpu_pci.h, viogpu/common/viogpu_queue.cpp, viogpu/common/viogpu_queue.h, viogpu/viogpudo/viogpudo.cpp, viogpu/viogpudo/viogpudo.h
Based on https://github.com/virtio-win/kvm-guest-drivers-windows/pull/943
=> RHEL-64314: [viogpu] Preparations for viogpu3d driver

contributing.md
1. Update `contributing.md` regarding `Tools/clang-format-helper.sh`
=> [doco] Update contributing.md re clang-format-helper.sh  [CI-NO-BUILD]

NetKVM/buildAll.bat, viostor/buildAll.bat
1. Fixes regressions introduced in PR #1240 (4502ac3) and PR #1241 (510167a).
My bad... 8^d
ATTN: @kostyanf14
=> [build] Fix for improper SDV Target parameter [SKIP-HCK-CI]

contributing.md
1. Emcourage all contibutors to add known Jira keys as a prefix to PRs
2. Expand examples and place in dropdown
=> [CI-NO-BUILD] [doco] Update contributing.md re Jira key prefix

NetKVM/netkvm-base.txt, build/Driver.Common.props
Not for merge - only for test on W10
=> [RHEL-78518]netkvm: disable DMA remapping for Win10 build

NetKVM/DebugTools/WMI/netkvm-wmic.cmd
Keeping old netkvm-wmi.cmd as netkvm-wmic.cmd
Use powershell commands to access WMI objects.
=> [CI-NO-BUILD] netkvm-wmi: use powershell for WMI operations

viofs/svc/virtiofs.cpp
When creating a VirtioFsSvc service using sc create, command-line arguments appear to be ignored.
To work around this, when argc <= 1, we can manually parse the full command line using GetCommandLineW and CommandLineToArgvW, restoring proper argc/argv behavior.
=> RHEL-95788: Fix- support CLI argument for VirtioFsSvc service

ivshmem/Device.c, ivshmem/Device.h, ivshmem/Driver.h
Remove code in ivshmem related to unsupported Windows versions.
=> RHEL-108838: [ivshmem] Remove code related to unsupported Windows versions
