virtio-win/kvm-guest-drivers-windows

Balloon/sys/Device.c

Commit 9b81256 added a call to WdfObjectAcquireLock which raises
IRQL to DISPATCH_LEVEL, but BalloonEvtFileClose still resides in
the PAGE section which requires IRQL <= APC_LEVEL to execute. This
commit fixes it by removing the function from the section. The
PAGED_CODE() macro - a bit of a misnomer because it checks IRQL
at function entry only, so technically it is still correct - is
removed also.
This is part of a fix for BZ #1419785.

balloon: Remove BalloonEvtFileClose from the PAGE section

---

viorng/cng/um/viorngum.c
viorng/coinstaller/viorngci.c

This is part of an effort to merge the stable branch (where Fedora and RHEL virtio-win drivers come from) into master.
No functional changes, cosmetic only.

Merge stable to master: viorng

---

vioscsi/helper.c
vioscsi/vioscsi.c
vioscsi/vioscsi.h
viostor/virtio_stor.c

This is part of an effort to merge the stable branch (where Fedora and RHEL virtio-win drivers come from) into master.
@vrozenfe please review. Should the "dont use cpu-to-vq map" commit use ifdefs to keep the cpu-to-vq map enabled only if explicitly requested, similar to #ifdef USE_WORK_ITEM? Thanks!

Merge stable to master: viostor and vioscsi

---

Balloon/sys/Device.c

The balloon worker thread may get starved and inflate/delate may
take an unreasonably long time if the system is under CPU stress.
This commit increases the base priority of the thread to
LOW_REALTIME_PRIORITY and adds the EVENT_INCREMENT dynamic priority
boost to all KeSetEvent calls.
Of course, there is no guarantee that the thread will be scheduled
and increasing the priority may be perceived as a peeing contest.
In this case though, given that the thread is idle and not scheduled
at all most of the time, and, in fact, logically an extension of the
DPC routine, higher priority is justified.

balloon: Boost worker thread priority

---

vioinput/hidpassthrough/hidpassthrough.c
vioinput/hidpassthrough/hidpassthrough.vcxproj
vioinput/hidpassthrough/hidpassthrough.vcxproj.filters
vioinput/hidpassthrough/pdo.h
vioinput/sys/Device.c
vioinput/sys/Hid.c
vioinput/sys/vioinput.h
vioinput/sys/vioinput.inx

The canonical KMDF HID driver uses mshidkmdf.sys (or its equivalent
viohidkmdf.sys) as the FDO for the device and the actual KMDF driver
as its lower filter to work around PnP KMDF limitations. This works,
except for the case where the same device, in terms of USB or PCI or
any other bus location, may expose different HID collections every time
it's plugged in. Because the instance path of the HID PDO (like for
example "HID-compliant mouse") is constructed only from the instance
path of the parent - likely just by replacing the bus ID with "HID" -
the system will reuse pre-existing devnodes, even if the HID collection
and the report descriptor are completely different and a keyboard,
for example, should be created instead of a mouse.
It's not hard to run into this issue with the vioinput …

vioinput: Switch from filter to bus/child architecture

---

vioscsi/vioscsi.c

The driver currently computes max_queues using the configured
number of queues and maximum CPUs supported by the system, even
in dump mode. This results in attempts to allocate excessive
amount of memory and VioScsiFindAdapter failing.
Note that StorPortGetUncachedExtension can only allocate a
maximum of 64 kB on some Windows versions.
We know that we always use only one queue in dump mode. This
commit fixes the code accordingly.

vioscsi: Allocate only one virtqueue in dump mode

---

Balloon/sys/balloon.props
Tools/Driver.Common.targets
Tools/Driver.RHEL.props
Tools/Driver.VZ.props
pvpanic/PVPanic Package/pvpanic_pack.props
pvpanic/pvpanic/pvpanic.props
vioinput/hidpassthrough/hidpassthrough.props
vioinput/sys/vioinput.props
viorng/VirtRNG Package/viorng_pack.props
viorng/cng/um/viorngum.props
viorng/coinstaller/viorngci.props
viorng/viorng/viorng.props
vioscsi/vioscsi.props
vioserial/sys/vioser.props
viostor/viostor.props

Defines a new CopyrightStrings property which is then used in
vendor specific files to compose copyright strings. This way
a new vendor FOO will define their copyright string policy in
Driver.FOO.props
foo.ver
etc.
without touching driver props files.
Keeping vendor specific properties in their separate files makes
introducing a new vendor a purely additive process, without the
need to edit existing files. The vendor may even keep their files
"downstream only" if they choose so.

Move {RHEL,VZ}_COPYRIGHT_STARTING_YEAR out of driver props files

---

NetKVM/Common/ParaNdis_GuestAnnounce.cpp

See RFC 5227
https://tools.ietf.org/html/rfc5227#section-2.3
https://tools.ietf.org/html/rfc5227#section-2.1.1
Target hardware address in ARP payload should be set to 0

netkvm: Set target hw address to zero in ARP announcement

---

vioserial/sys/Device.c
vioserial/sys/Port.c
vioserial/sys/vioser.h

This work was prompted the crash reported in
https://bugzilla.redhat.com/show_bug.cgi?id=1419900
vioserial: Introduce VIOSerialDrainQueue
If VIOSerialFillQueue fails, its effects need to be undone.
VIOSerialFillQueue is called from D0 entry callbacks, which are
not followed by D0 exit callbacks on failure, so the buffers that
may have been added to the queue need to be freed within the D0
entry.
This commit adds a new function VIOSerialDrainQueue to take care
of freeing buffers on the queue. In addition do the D0 exit
callbacks, the new function is called from VIOSerialFillQueue
when it's about to return a failed NTSTATUS.
vioserial: Propagate D0 entry failure from device to ports
From the "Reporting Device Failures" MSDN page:
If a bus driver's EvtDeviceD0Entry function returns a value …

vioserial: Improve error handling

---

Balloon/sys/balloon.c

Some HCK tests can still crash the driver by running the
BalloonEvtFileClose callback in parallel with
BalloonEvtDeviceD0Entry. BalloonEvtFileClose uses the value
of StatVirtQueue to check whether the device is up. In the
pathological case, this field is still non-NULL when
BalloonEvtFileClose reads it, but the device is terminated
before it has a chance to finish sending the stats to the host.
In commit 9b81256 explicit device-level synchronization was
added to BalloonEvtFileClose which was believed to solve this
assuming that power callbacks are synchronized automatically.
MSDN says that "The framework always synchronizes each device's
PnP and power management callback functions." but it only means
that the callbacks are synchronized with each other.
This commit adds explicit …

balloon: Put BalloonInit and BalloonTerm under device lock

---

NetKVM/Common/ParaNdis-TX.cpp

In case the NBL shall be completed from the destructor of CNBL
object, the access causes BSOD.

netkvm: Fix wrong access to zeroed m_NBL member

---

Balloon/sys/utils.c
NetKVM/Common/ParaNdis-Debug.cpp
vioinput/sys/utils.c
vioscsi/utils.c
vioserial/sys/utils.c
viostor/virtio_stor_utils.c

According to documentation the va_end macro should be invoked before
the function returns whenever va_start has been invoked from that
function.
This commit fixes errors reported by cppcheck tool.
Error sample:
[kvm-guest-drivers-windows/Balloon/sys/utils.c:60]: (error) va_list 'list'
was opened but not closed by va_end().

Add missing invokes to va_end macro

---

vioscsi/helper.c
vioscsi/vioscsi.c
vioscsi/vioscsi.h
vioscsi/virtio_pci.c

This is a follow-up to https://github.com/virtio-win/kvm-guest-drivers-windows/pull/103 where we decided to keep the simplified locking logic and complete requests in DPC even when running with only one queue.

vioscsi: DPC fixes

---

VirtIO/WDF/PCI.c
VirtIO/WDF/VirtIOWdf.c
VirtIO/WDF/private.h
vioserial/sys/Device.c

This is a workaround for a WDF bug, last seen in version 1.9 and
confirmed fixed in 1.11. On resource rebalance WDF does not
preserve the MessageNumber field of its internal data structures
describing interrupts. As a result, we fail to report the right
MSI message number to the virtio device when re-initializing it
and it may stop working.
This manifests as a hang while trying to write to a virtual serial
port after a CPU is hotplugged to Windows 2008 R2, for example.
The fix is to keep the message number in a separate context
structure, attached to the interrupt object the first time it is
passed to us. Getting the message number can be subsequently
satisfied from this context, rather than from the buggy
WdfInterruptGetInfo call.
---
The first commit is a fix for …

virtiolib: Remember interrupt message numbers

---

NetKVM/netkvm.inf

Currently in order to configure the Vlan Id property we need to add it
manually to the registry and then change it from the device's advanced
tab. This commit solves this issue by adding the property to the Inf file
which adds it automatically to the registry upon driver installation.

BZ#1438410 - Net-KVM: Add VlanId property to Inf file

---

vioscsi/vioscsi.c
viostor/virtio_stor.c

The "pool" region of the uncached extension is meant to follow the
"page" region but due to a bug the two could overlap, leading to
memory corruptions.
adaptExt->pageAllocationVa is page-aligned and may be greater than
uncachedExtensionVa. adaptExt->poolAllocationVa must use the page-
aligned value to compute the end of the page region.
The bug was introduced in commit 4ab136a0 and then copied to viostor
as part of the MQ work.
cc @vrozenfe

Viostor/vioscsi: Fix uncached extension layout

---

NetKVM/wlh/ParaNdis6-Oid.cpp

https://bugzilla.redhat.com/show_bug.cgi?id=1439085
WLK 1.6 does not recognize filter for '1c_wmicoverage' test
which fails if network driver supports custom OIDs mapped
to WMI GUIDs (on later operating systems and HCK 2.1 and up the
test also fails but the failure filtered properly).
Current commit disables custom OIDs for Vista/2008 to let all
certification tests pass.

netkvm: Disable WMI custom OIDs for Vista/2008

---

Tools/pushpdb.cmd

Win8.1 SDK may not be installed on virtio-win build machines.
Use Win10 instead.
cc @YanVugenfirer cc @bish22ah

pushpdb: Use Win10 SDK

---

viostor/virtio_stor.c

The static driver verifier build flags this as a potential NULL
dereference. If SRB_GET_SENSE_INFO_BUFFER fails senseBuffer will
be NULL.
viostor\virtio_stor.c(1342): warning C6011: Dereferencing NULL pointer 'senseBuffer'.
cc @vrozenfe

viostor: Fix potential NULL dereference

---

NetKVM/netkvm_no_RSC.inf
NetKVM/netkvm_no_RSS.inf

This commit adds the vlan id property to the netkvm_no_RSS.inf and
netkvm_no_RSC files.

BZ#1438410 - Net-KVM: Add VlanId property to no_RSS and no_RSC Inf files

---

vioinput/sys/Array.c
vioinput/sys/Hid.c
vioinput/sys/HidMouse.c
vioinput/sys/vioinput.h

Fixes for virtio-input bugs found with a random input device generator.
https://github.com/ladipro/linux/blob/input_fuzzer/drivers/input/misc/input-fuzzer.c
The test re-loads the input-fuzzer module in a loop, attaching the evdev device to a Windows VM and using the QEMU guest agent to execute "devcon status" to see if the guest driver is loaded without errors.

vioinput: Fuzz testing fixes

---

pciserial/buildAll.bat
pciserial/qemupciserial.inf
pciserial/rhel/qemupciserial.inf

The combined pci-serial & pci-serial-2x & pci-serial-4x .inf
file cannot pass WHQL tests due to what looks like a bug in
MF.sys (Windows inbox component).
https://bugzilla.redhat.com/show_bug.cgi?id=1443019
This commit adds an alternative version of the file based on
what was shipped in RHEL 7.3. RHEL QEMU supports only the
single-port device (-device pci-serial) so it can get away
without the MF.sys dependency for now.
Here's the diff between RHEL 7.3 qemupciserial.inf and the new file:
```
4c4
< ; just a inf file to tell windows which pci id the serial pci card
---
> ; just a inf file to tell windows which PCI ID the serial PCI card
8,11c8,11
< ; Installing the driver: Go to device manager.  You should find a "pci
< ; serial card" tagged …
```

pciserial: Add a pci-serial (1x only) .inf for RHEL

---

Q35/SMBus/smbus.inf
Q35/buildAll.bat
Q35/clean.bat
buildAll.bat
clean.bat

The device 8086:2930 has no built in driver in Windows 2008 and Win7 on
both x86 and x64 architectures, this commit adds a suitable null driver
for this device.
Signed-off-by: Sameeh Jubran <sjubran@redhat.com>
Signed-off-by: Daniel Rempel <daniel@daynix.com>

BZ#1393772: Add null driver for SM Bus Controller

---

Balloon/app/blnsvr.props

The file should have been added as part of commit 30e58ef. The
balloon service project fails to load and build without it.

balloon: Add missing blnsvr.props

---

NetKVM/Common/ParaNdis-Common.cpp
NetKVM/Common/ndis56common.h
NetKVM/Common/virtio_net.h

The new virtio-net spec introduces a new MAX MTU configuration field to
the device's configuration area. It is used to pass a maximum MTU
from the device to the driver.
Signed-off-by: Sameeh Jubran <sjubran@redhat.com>

Net-KVM: Implement "MTU report" feature of the device

---

VirtIO/WDF/Callbacks.c

All implementations of mem_alloc_nonpaged_block except for WDF
return zero-inited memory. Make WDF do the same.
This commit fixes ACCESS_VIOLATION BSOD observed in:
https://bugzilla.redhat.com/show_bug.cgi?id=1455488
where mem_alloc_nonpaged_block is called by
virtio_reserve_queue_memory and virtio_delete_queues then
runs before all queues have been fully set up.

virtiolib: Make WDF mem_alloc_nonpaged_block return initialized memory

---

Balloon/sys/Device.c

When the device power state is changed, or during the hardware resources
rebalancing (occurs after cpu hotplug, for example), BalloonEvtDeviceD0Entry
can be called again after BalloonEvtDeviceD0Exit. In this case, guest will
BSOD after the first Isr Dpc. In addition StatWorkItem is created in
BalloonDeviceAdd and will be automatically deleted by the framework along
with the device, so setting StatWorkItem to NULL in BalloonEvtDeviceD0Entry
is simply incorrect.
About a year ago AlekseyKostyushko already made a similar patch, which also
synchronize Dpc activity with D0Entry / D0Exit. Our tests and framework code
analysis showed that wdf really waits the Dpc rundown before D0Exit call so
additional synchronization is not required. …

Balloon: Remove devCtx->StatWorkItem=NULL from D0Exit

---

NetKVM/Common/ParaNdis-TX.cpp
NetKVM/Common/ParaNdis_GuestAnnounce.cpp
NetKVM/Common/ParaNdis_GuestAnnounce.h

https://bugzilla.redhat.com/show_bug.cgi?id=1458626
When sending ARP packets out upon migration it is possible
that previously sent packet is still not completed when
host requests to send another one. In this case sending
the same NBL/NB again is not acceptable as the NB is still
mapped by HAL and double mapping/unmapping is not supported
by the operating system and causes BSOD on second unmapping.
In current commit we always send a clone of originally created
ARP NBL, using MDL/buffer of original (prototype) NBL.
This commit also fixes usage by NdisReserved field of NBL and
uses MiniportReserved instead.

netkvm: Send clone of original announcement NBL

---

NetKVM/Mof/Mof.vcxproj
NetKVM/Mof/clean.bat
NetKVM/clean.bat
VirtIO/clean.bat
vioinput/cleanAll.bat

```
This commit fixes a few issues with the clean.bat / cleanAll.bat
scripts. All output and intermediate files are now deleted upon
executing clean.bat in the root of the repo.
Absolute IntDir and OutDir paths are added to NetKVM/Mof/Mof.vcxproj
to avoid leaving build artifacts in random directories.
```
Longer term, it would be nice to have the MSBuild Clean task do this work since the build knows what files it generates. Then we would be able to delete all these batch files.

Fix cleanup scripts

---

NetKVM/Common/ParaNdis-Common.cpp
NetKVM/Common/ParaNdis-Debug.cpp
NetKVM/Common/ParaNdis-TX.cpp
NetKVM/Common/ParaNdis-Util.cpp
NetKVM/Common/ParaNdis-Util.h
NetKVM/Common/osdep.h
NetKVM/wlh/ParaNdis6-Driver.cpp
NetKVM/wlh/ParaNdis6-Impl.cpp
NetKVM/wlh/ParaNdis6-Oid.cpp

It turns out that none of the warning suppression #pragma's in the network driver are necessary. The first patch adds proper SAL annotation, the second patch deletes all #pragma warning's, and the last one is a small cleanup in osdep.h.

NetKVM warning cleanup

---

Tools/Driver.Common.targets

stampinf.exe in the latest Win10 WDK appears to have a bug and writes
out an empty DriverVer= directive when passed a command line like below:
stampinf -f <inf> -a <arch> -v <version>
Adding -d seems to work around it:
stampinf -f <inf> -a <arch> -v <version> -d *
---
Reported by @jackli577 in https://github.com/virtio-win/kvm-guest-drivers-windows/issues/159

Fix build break with WDK 10.0.15063.0

---

Balloon/app/memstat.cpp

Setting vt to -1 does not produce a valid VARIANT. An exception is thrown
when one tries to extract data from such a variable.
The code was very likely intended to set the value to -1, which is the
unofficial "missing" marker used by QEMU.

balloon: Don't create invalid VARIANTs

---

viostor/virtio_pci.c
viostor/virtio_stor.c
viostor/virtio_stor.h

device.
The following patch fixes problem with config MSI message processing.
While this bugfix works as expected for the most of the use cases,
there is still a problem with one vestor configuration reported in
Bug 1451572 - [virtio-win][viostor] can not resize the disk with
"-device virtio-blk-pci, ..., vectors=1"
This problem is a special case that probably will be addressed in
a separate patch.

Fix for BZ#1442322 - Cannot enlarge/shrink disk with virtio-blk-pci

---

NetKVM/Common/ParaNdis-Common.cpp
NetKVM/netkvm.inf

I have mistakenly pushed a partial commit earlier (https://github.com/virtio-win/kvm-guest-drivers-windows/commit/5eb813024e0a7a915a5cb39687c5dee80ef123e0), this is the remains of it.

Net-KVM: Fix a typo in the configuration entry settings

---

vioscsi/utils.c
vioscsi/vioscsi.c
viostor/virtio_stor.c

Most of the changes in this patch are to prevent SDV from complaining
about NULL pointer accesses, and don't need any explanation. However,
the change about max_cpus and num_cpus warrants some explanation. The
problem is that the SDV complains that the vioscsi and viostor drivers
fail the StorPortSpinLock3 rule. Debugging showed that the SDV does not
understand the value returned by KeQueryMaximumProcessorCountEx(). That
function is expected to return a ULONG value, but SDV does not correctly
interpret the returned value. That results in num_queues ending up as
zero, which in turn results in MaxIOsPerLun and InitialLunQueueDepth in
the PORT_CONFIGURATION_INFORMATION structure being set to zeroes, and
that makes SDV conclude that the driver is failing the StorPortSpinLock3
rule. Tried …

Changes to keep "Static Driver Verification" (SDV) happy.

---

vioserial/sys/Control.c
vioserial/sys/Device.c
vioserial/sys/Port.c
vioserial/sys/vioser.h

This patch is a fix for very annoying problem in the production. It was
very hard to understand what is going on and why. From the user point
of view the situation looks like
dev: virtserialport, id "channel0"
chardev = "charchannel0"
nr = 1 (0x1)
name = "org.qemu.guest_agent.0"
port 1, guest off, host off, throttle off
and the device comes into this state under unknown circumstances.
We've found out that this problem is caused by a breakdown in the
control channel. The host has stopped responding to the control messages
at some moment. Sometimes channel could be fixed after qemu-qa service
restart, sometimes not. From the technical point of view there is the
following problem:
The amount of virtqueue_get_buf calls from VIOSerialSendCtrlMsg is
limited to RETRY_THRESHOLD times(400). …

serial: remove RETRY_THRESHOLD limit from c_ovq poll loop

---

buildAll.bat
ivshmem/Device.c
ivshmem/Queue.c
ivshmem/ivshmem.vcxproj
ivshmem/ivshmem.vcxproj.filters
ivshmem/test/ivshmem-test.vcxproj
ivshmem/test/ivshmem-test.vcxproj.filters

A few fixes to try to make the SDV build succeed. It has found real code issues.
I still haven't been able to make SDV generate the DVL file though. Running
`tools\build.bat ivshmem\ivshmem.vcxproj "Win10_SDV"`
fails with
```
"C:\kvm-guest-drivers-windows\ivshmem\ivshmem.vcxproj" (sdv target) (1) ->
(sdv target) ->
C:\Program Files (x86)\Windows Kits\10\build\windowsdriver.Sdv.targets(132,9): error MSB3073: The command "staticdv /devenv /check" exited with code -1. [C:\kvm-guest-drivers-windows\ivshmem\ivshmem.vcxproj]
0 Warning(s)
1 Error(s)
```
and it seems to be caused by one of the tools looking for sdv-harness.c.rawcfgf in ivshmem\sdv\check\purekmdfdriver instead of ivshmem\sdv where another tool puts it. So very likely a WDK bug. @gnif, do you see the same thing? Thanks!

SDV ivshmem fixes

---

ivshmem/Queue.c

If a second application opens and then closes the device handle the cleanup will enter an infinite loop. This patch fixes this.

[ivshmem] fixed infiniate loop bug

---

ivshmem/test/ivshmem-test.cpp

ivshmem-test.cpp(180): warning C4244: 'argument': conversion from 'IVSHMEM_SIZE' to 'std::size_t', possible loss of data
ivshmem-test.cpp(98): warning C4477: 'printf' : format string '%u' requires an argument of type 'unsigned int', but variadic argument 1 has type 'IVSHMEM_SIZE'
ivshmem-test.cpp(98): note: consider using '%llu' in the format string
ivshmem-test.cpp(98): note: consider using '%I64u' in the format string1
CC @gnif

ivshmem: Fix integer width warnings in ivshmem-test

---

vioserial/sys/Control.c

1. Counter variable (int cnt) is now unused and should be deleted.
2. Using KeDelayExecutionThread with zero timeout interval cause current thread
to relinquish the remainder of its time slice to other thread in most cases.
This allows to make small delay on PASSIVE_LEVEL and optimize CPU usage.
It looks slightly more efficient then using KeDelayExecutionThread which is
actually a busy loop.

serial: Minor corrections according to ladipro comments

---

ivshmem/test/ivshmem-test.vcxproj

Tools like this should run on clean installed systems. They should
not depend on CRT DLLs.

ivshmem: Link ivshmem-test against the static CRT

---

Balloon/sys/balloon.c

Patch 1 addresses a concern that the driver may be spending more time in the DPC than necessary due to contention on the queue spin locks (https://bugzilla.redhat.com/show_bug.cgi?id=1453090).
Patch 2 fixes a potential deadlock found while working on patch 1.

Minor balloon fixes

---

NetKVM/NDIS5/tools/signing.cmd
NetKVM/NetKVM-VS2015.vcxproj
Q35/buildAll.bat
Tools/Driver.PackOne.targets
fwcfg/buildAll.bat
pciserial/buildAll.bat

The inf2cat tool uses the UTC timezone by default for timestamp comparison,
this can cause the following error when there is a mismatch between time on
the build machine is and the one in UTC timezone. Using /uselocaltime
parameter solves this issue.
Inf2cat error:
* DriverVer set to incorrect date (postdated DriverVer not allowed) in
\netkvm.inf. The current date (UTC) is 01/01/2017.

Inf2cat: Use /uselocaltime when compiling

---

NetKVM/Common/ParaNdis-Common.cpp
NetKVM/wlh/ParaNdis6-Impl.cpp

Even though I don't see why anyone would use 2 msi vectors for the device, the driver should handle this successfully.

NetKVM: Fix a bug where driver won't load with 2 msi vectors

---

Balloon/sys/balloon.inx
README.md
Tools/Driver.Common.targets
Tools/Driver.RHEL.props
Tools/Driver.VZ.props
Tools/Driver.Vendor.props
ivshmem/ivshmem.inf
ivshmem/ivshmem.props
vioinput/sys/vioinput.inx
viorng/viorng/viorng.inf
vioscsi/vioscsi.inx
vioserial/sys/vioser.inx
viostor/viostor.inx
viostor/viostor_no_msi.inx

It is important that all parties shipping virtio-win drivers use their
own vendor-specific HW ID to avoid driving somebody else's device.
This is especially critical for WHQL'ed drivers distributed with Windows
Update, as these could be installed without any explicit user action.
A new build warning is introduced to make this requirement more
discoverable (suggested by @dlunev, thanks!)
Note that NetKVM has not been plugged into the new build infrastructure
yet so it is not handled by these commits.

Update README and parameterize PCI subsystem vendor ID

---

VirtIO/VirtIOPCICommon.c

Currently the DPrintf inside vp_notify is called at level 0,
the vp_notify is usually called many many times during normal
execution of the code, this debug print shouldn't be printed
during typical run as it may cause performance issues.

VirtIO: Change vp_notify debug print to a higher level

---

NetKVM/Common/ndis56common.h
NetKVM/wlh/ParaNdis6-Driver.cpp

Aligning shared data can affect performance as it might reduce cache
misses which result in performance gain.
According to msdn documentation NdisGetSharedDataAlignment returns boundary
value, in bytes, on which drivers should align structures that can be shared
by more than one processor.

NetKVM: Use NdisGetSharedDataAlignment to align miniport's adapter context

---

NetKVM/Common/ParaNdis-TX.cpp
NetKVM/Common/ParaNdis-TX.h
NetKVM/NetKVM-VS2015.vcxproj
NetKVM/NetKVM-VS2015.vcxproj.filters
NetKVM/ParaNdis_LockFreeQueue.h

This patch series introduces a lock free queue into NetKVM and uses it in TX when receiving NBLS (packets) from Windows. Currently the queue is a multiple producer single consumer queue, this can be extended in the future to a multiple consumer queue.

Introduce lockless queue into NetKVM

---

ivshmem/Device.c

WDFINTERRUPT objects are deleted by the framework. Explicitly calling
WdfObjectDelete results in an assert/BSOD when running with Driver
Verifier enabled.
---
Note that the **Creating an Interrupt Object** MSDN article at https://docs.microsoft.com/en-us/windows-hardware/drivers/wdf/creating-an-interrupt-object is wrong. WdfObjectDelete must not be called on interrupts:
https://github.com/Microsoft/Windows-Driver-Frameworks/blob/master/src/framework/shared/irphandlers/pnp/interruptobject.cpp#L234
cc @gnif

ivshmem: Don't delete WDFINTERRUPTs

---

NetKVM/Common/ParaNdis-TX.cpp

The ASSERT macro is defined as ((void) 0) and thus whatever inside it
doesn't get executed when compiling release.
For the reason explained above, NBLs from the lock free queue weren't
poped from the queue after performing peek operation, this caused
the driver to hang in an infinite loop when running release.

NetKVM: Fix hang in release

---

NetKVM/ParaNdis_LockFreeQueue.h

We should compare the consumer's head to the producer's tail.

NetKVM: LockFreeQueue: Fix Peek method

---

Tools/Driver.PackOne.targets

Now PackOne takes files from objchk_* and copy them to Install_Debug when project configuration name ends with "Debug". It's required for NDIS5 driver build.
Also, PackOne source and dest can be overrided in the project configuration.

build: Debug config support for PackOne

---

vioserial/sys/Port.c

Virtio serial ports receive the D0 exit callback before the parent driver.
This is expected in this driver architecture of a parent bus driver and
ports modeled as children. It however causes issues because ports own their
respective queues and try to clean them up while VirtIO as a whole, to be
shut down by the master D0 exit callback, is still running.
As a result, D0 exit (caused by resource rebalance on CPU hot-plug for
example), may crash QEMU with errors similar to:
Looped descriptor
or
Guest moved used index from 253 to 176
because port D0 exits race with QEMU still pushing data to the queues.
This patch fixes it by sending the VIRTIO_CONSOLE_PORT_OPEN control message
with open=0, i.e. signaling to the host that the port is closed and should
not be receiving more traffic.
It would …

vioserial: Send VIRTIO_CONSOLE_PORT_OPEN (0) on port D0 exit

---

NetKVM/Common/ParaNdis-VirtIO.cpp
VirtIO/VirtIORing.c

Fixes two asserts that fire when a debug build of NetKVM is started.

Fix asserts in VirtioLib and NetKVM

---

vioscsi/vioscsi.c
vioscsi/vioscsi.h
viostor/virtio_stor.c
viostor/virtio_stor.h

The drivers were using indirect virtqueue buffers if the feature was offered by the device but they never acked it which is a spec violation.
The VIRTIO_RING_F_INDIRECT_DESC macro is already defined in virtio_ring.h, the commits also delete extra copies.

viostor, vioscsi: Ack the VIRTIO_RING_F_INDIRECT_DESC feature

---

NetKVM/Common/ParaNdis-AbstractPath.h
NetKVM/Common/ParaNdis-RX.cpp
NetKVM/Common/ParaNdis-RX.h
NetKVM/Common/ParaNdis-SM.h
NetKVM/Common/ParaNdis-TX.cpp
NetKVM/Common/ParaNdis-TX.h
NetKVM/Common/ParaNdis-Util.h

The NdisDprAcquireSpinLock and NdisDprReleaseSpinLock are an optimized
version of the Ndis Acquire and Release functions that should be called
only at Dispatch level.

NetKVM: Use Ndis DPC level spinlock functions

---

Balloon/sys/balloon.c
NetKVM/Common/ParaNdis-CX.cpp
NetKVM/Common/ParaNdis-Common.cpp
NetKVM/Common/ParaNdis-RX.cpp
NetKVM/Common/ParaNdis-TX.cpp
NetKVM/Common/ParaNdis-VirtQueue.cpp
NetKVM/Common/ParaNdis-VirtQueue.h
NetKVM/Common/ndis56common.h
NetKVM/NDIS5/Common/ParaNdis-Common.c
NetKVM/NDIS5/Common/ndis56common.h
NetKVM/NDIS5/wxp/netkvm.inx
VirtIO/VirtIO.h
VirtIO/VirtIOPCICommon.c
VirtIO/VirtIORing.c
VirtIO/WDF/VirtIOWdf.c
VirtIO/WDF/VirtIOWdf.h
VirtIO/virtio_pci.h
vioinput/sys/Device.c
viorng/viorng/power.c
vioscsi/vioscsi.c
vioserial/sys/Device.c
viostor/virtio_stor.c

There's no point in telling VirtioLib about the event suppression setting using  virtio_set_queue_event_suppression() or the bEnableInterruptSuppression field. VirtioLib can detect the presence of the VIRTIO_RING_F_EVENT_IDX feature (as acked by the driver) internally.
This series removes the API and all its uses, which simplifies all drivers.

Simplify event suppression

---

VirtIO/VirtIORing.c

A small tweak to VirtioLib to make the available ring flags write-
only, as originally intended.
Fixes:
commit 71405a229ef98ddcb7937953b063dfd163bfaea1
Author: Ladi Prosek <lprosek@redhat.com>
Date:   Tue Aug 1 08:51:58 2017 +0200
virtiolib: Rewrite VirtIORing.c

virtiolib: Don't read vring avail flags

---

vioinput/sys/Device.c

The virtio-input driver has the same bug as virtio-serial, see
https://bugzilla.redhat.com/show_bug.cgi?id=1520352.
It's much harder to hit it with virtio-input because of its much lower
data rate and, to a smaller extend, also a smaller number of "receive"
buffers that can be pushed on the event queue (64 vs. 128 in virtio-
serial).
The fix here is simply to reset the device before touching the event
queue with virtqueue_detach_unused_buf() so it doesn't race with the
device processing it. With virtio 1.0, the reset is synchronous (the
driver waits for the reset to be acknowledged by the device) and
virtio-input is exposed as a virtio 1.0-only device.
Long-term it may be nicer to eliminate the virtqueue_detach_unused_buf()
API altogether and have the drivers track what's been pushed with …

vioinput: Reset device before detaching unused buffers

---

VirtIO/linux/virtio_types.h
VirtIO/virtio_pci.h
VirtIO/virtio_ring.h

Search for the Linux imported header files in the local directory and not in the global Include files one.

virtiolib: fix compilation error

---

NetKVM/Common/ParaNdis-CX.cpp
NetKVM/Common/ParaNdis-Common.cpp
NetKVM/Common/ParaNdis-SM.h
NetKVM/Common/ndis56common.h
NetKVM/wlh/ParaNdis6-Driver.cpp

The following assumption in CParaNdisCX::SendControlMessage:
"Control messages are processed synchronously in QEMU, so upon kick_buf
return, the response message has been already inserted in the queue"
Is not true, so we need to wait until the buffer is
returned by the virtqueue.
Prior to this patch the debug build of NetKVM would flood the logs
on startup of the device with the message:
"CParaNdisCX::SendControlMessage - ERROR: add_buf failed"
The driver would fill the virtqueue by not waiting for the buffers to
return due to the misleading assumption above which lead the queue to
become overflawed that caused failure in adding buffers to the queue.
This assumption seems to be true with vhost=on as this doesn't reproduce
with vhost=on.

CParaNdisCX: SendControlMessage: Make sure the buffer is returned

---

.appveyor.yml

The commit disables the run of SDV checks during ci build as they are consuming a long execution time. These checks lead to reaching the maximum allowed time for build execution time for our current plan - 60 minutes - what mistakenly cause failures to show up.

Appveyor CI: Don't run SDV checks on Build

---

NetKVM/CoInstaller/NetKVMnetsh.cpp
VirtIO/WDF/Callbacks.c
VirtIO/WDF/PCI.c
pvpanic/pvpanic/power.c
pvpanic/pvpanic/pvpanic.c
pvpanic/pvpanic/pvpanic.h
vioinput/hidpassthrough/hidpassthrough.c
vioinput/sys/Device.c
vioinput/sys/Driver.c
vioinput/sys/HidKeyboard.c
vioinput/sys/KeyMap.c
viorng/viorng/viorng.h

Fixes an assortment of issues found by running the static analysis build.
It uncovered two bugs in vioinput and several places where we allocated executable memory. The rest is mostly tweaks.
With this and the other two static analysis pull requests all included, the remaining list of issues is small and mostly non-actionable:
```
1>c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\string.h(130): warning C28252: Inconsistent annotation for 'strcpy': _Param_(1) has 'SAL_writableTo(elementCount(_String_length_(__formal(1,parameter1))+1))' on the prior instance. See <no file>(0). 
1>c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\string.h(130): warning C28253: Inconsistent annotation for 'strcpy': _Param_(1) has …
```

pvpanic, vioinput, viorng, virtiolib, netkvm: Static analysis fixes and tweaks

---

NetKVM/Common/ParaNdis-Common.cpp

This bug caused by historical refactoring done in
ParaNdis_InitializeContext function. If PCI resource initialization failed
driver should not continue execution of ParaNdis_InitializeContext
function.

netkvm: driver should fail initialization if PCI resources init failed

---

NetKVM/Common/ParaNdis-Common.cpp

The bug was caused by a bug in the backend where the driver allocates more
than one hardqueue and doesn't enable all of them which leads the backend
crashing. When RSS is not enabled in compilation the driver uses one queue
only, this commit drops MQ support when the driver has RSS disabled which
prevents these unnecessary allocations.
Closes 230
Signed-off-by: jackli <1744764178@qq.com>

netkvm: Driver should not indicate MQ support when RSS isn't supported

---

ivshmem/Device.c
ivshmem/Public.h
ivshmem/Queue.c

This PR performs two things:
* moves ioctl code from the large switch statement into local static functions
* Adds `IVSHMEM_MMAP_CONFIG` to the `IVSHMEM_REQUEST_MMAP` IOCTL which allows specifying the cache type rather then always assuming write combining.

Cleanup of IVSHMEM and add ability to specify cache type

---

NetKVM/Common/ParaNdis-Common.cpp
NetKVM/Common/ndis56common.h
NetKVM/Common/osdep.h
NetKVM/Common/virtio_net.h
NetKVM/netkvm.inx
NetKVM/netkvm_no_RSC.inx
NetKVM/netkvm_no_RSS.inx
NetKVM/wlh/ParaNdis6-Driver.cpp
NetKVM/wlh/ParaNdis6-Oid.cpp

Changes following the introduction of virtio's flag, VIRTIO_NET_F_SPEED_DUPLEX,
which allows the host to set the LinkSpeed/Duplex values.
Up until this stage the configurations of LinkSpeed/Duplex used were hardcoded,
with default LinkSpeed=10Gbits/s, Duplex=full.
But uppon the introduction of VIRTIO_NET_F_SPEED_DUPLEX, it'll be more useful to
import them from the host and apply them if the VIRTIO_NET_F_SPEED_DUPLEX is on,
or, use the default configurations if it is off:
(LinkSpeed=10Gbits/s, Duplex=full).
Changes also includes removing the ConnectRate parameter from the inf file as we
never saw that it was used.
Qemu patches:
1. [v4,2/3] qemu: virtio-net: use 64-bit values for feature flags:
https://patchwork.ozlabs.org/patch/856266/
2. [v4,3/3] qemu: add linkspeed and duplex settings to …

NetKVM: BZ#1537430 Import LinkSpeed/Duplex configs from the hypervisor

---

Balloon/app/blnsvr.props
Balloon/app/blnsvr.vcxproj
NetKVM/CoInstaller/netkvmco-vs2015.vcxproj
Tools/Driver.Common.props
viorng/VirtRNG Package/VirtRNG Package.vcxproj
viorng/VirtRNG Package/viorng_pack.props
vioserial/app/vioser-test.props
vioserial/app/vioser-test.vcxproj

All driver for Windows 10 will be built for "Universal" target platform.
Exceptions:
* viorng - currently coninstaller is used to register user mode components for viorng. The usage of coinstallers is not allowed with "Universal" platform.
* Balloon service - still uses non-universal API.
* netsh plugin that is provided with NetKVM  - still uses non-universal API.

All driver for Windows 10 will be built for "Universal" target platform.

---

Tools/Driver.Common.props

Due to the time difference between local time and UTC, compilation might fail.

Run inf2cat with localtime command line option

---

vioinput/sys/HidMouse.c

All relative axes including mouse wheels are ignored whenever REL_X and
REL_Y inputs are missing, such as for virtio-tablet-pci devices. This
patch restores support for all relative axes in tablet mode.
Signed-off-by: Justin Gatzen <justin.gatzen@gmail.com>

vioinput: Allow mouse wheels and other relative axes on tablets

---

Tools/signAll.bat

this script will sign all drivers with the certificate found at VirtIOTestCert.pfx.
this is used to practice a CI workflow automating microsoft HCK/HLK tests.
Signed-off-by: 20lives <lior@dotcore.co.il>

adding a certificate sign script to all drivers

---

Tools/signAll.bat

files and folders with spaces got messed up, this fixes the issue.
Signed-off-by: 20lives <lior@dotcore.co.il>

Dealing with white spaces in files path on cert sign script

---

NetKVM/Common/ParaNdis-Common.cpp
VirtIO/linux/virtio_config.h

Background: https://issues.oasis-open.org/browse/VIRTIO-154 , we want that virtio-win drivers will use only DMA API for shared memory allocation (where possible, the balloon might be an exception).
This is the first set of patches adding VIRTIO_F_IOMMU_PLATFORM flag and acking the flag in NetKVM.
More changes for other drivers to follow.

NetKVM to support ACK of VIRTIO_F_IOMMU_PLATFORM

---

vioscsi/vioscsi.c
viostor/virtio_stor.c

Background: https://issues.oasis-open.org/browse/VIRTIO-154 , we want that virtio-win drivers will use only DMA API for shared memory allocation (where possible, the balloon might be an exception).
This is the second set of patches adding VIRTIO_F_IOMMU_PLATFORM flag and acking the flag in storage related drivers.

viostor and vioscsi to support ACK of VIRTIO_F_IOMMU_PLATFORM

---

viostor/virtio_stor.c

The STORAGE_REQUEST_BLOCK is the extended format SCSI Request Block (SRB) structure. The structure provides for the addition of extended data associated with an SRB function.

enable and properly handle storage request block SRB type

---

Balloon/sys/memstat.c

Balloon.sys build failed, when USE_BALLOON_SERVICE is not defined, because of
include <memstat.tmh> missing.

Build: Balloon build fixed

---

Tools/Driver.Common.props

The wppmodulename is the friendly name of the message GUID. The
friendly name of the message GUID appears, by default, in the trace
message prefix.
By default, the friendly name of the message GUID is the name of
the directory in which the trace provider was built, this causes
some drivers as "sys". This commit overrides the default value
by setting the wppmodulename to be project name.

WPP Tracing: Set wppmodulename as project name

---

fwcfg64/driver.c
fwcfg64/driver.h
fwcfg64/power.c

After this patch driver can expose crashdump header with pointer to
decoded KdDebuggerDataBlock. In addition to producing crashdump at BSOD time,
QEMU using this structure can create valid live system dump.
Signed-off-by: Viktor Prutyanov <viktor.prutyanov@virtuozzo.com>

fwcfg64: add decoded KdDebuggerDataBlock exposure

---

fwcfg64/cleanAll.bat
fwcfg64/fwcfg.inf
fwcfg64/fwcfg.props
fwcfg64/fwcfg.vcxproj

I think, PackOne is a better way to place driver files into Install dir.

fwcfg64: Using PackOne instead of PostBuildEvent

---

viostor/virtio_stor.c
viostor/virtio_stor_hw_helper.c

Two things in this series:
- redesign vq lock/unlock routines. Same as in virtio-scsi driver, should give some performance improvement on small (4K) block transfers. 
- Bugfix for Bug 1566298 unattended installation failure on upartitioned image
Vadim,

Viostor driver update

---

NetKVM/Common/ParaNdis-Common.cpp

VIRTIO_NET_F_STATUS off misbehaviours fixed:
1. Reading the current link state,
fix: ReadLinkState is not to be called in this case.
2. Link state is not initialized,
fix: pContext->bConnected initialized to TRUE.

NetKVM: Fixing behaviour when VIRTIO_NET_F_STATUS is off

---

NetKVM/Common/ParaNdis-Common.cpp
NetKVM/Common/ParaNdis-TX.cpp
NetKVM/Common/ParaNdis-TX.h

In commit e8f319fdc09837dc27fce1b8abb3496593e9dc10 the lock free queue was
introduced as an alternative implementation to the previous one which
required acquiring the TX's path lock for NBLs sent by Windows. The
intention for the implementation introduced was that this lock acquirement
would be dropped in favour of scheduling a DPC upon sending an NBL instead.
While this DPC scheduling approach works it does introduce a heavy DPC
scheduling on the environment, the overhead can be as high as executing a
DPC for each NBL sent by Windows in the worst case scenario. In general
Windows should drop duplicate DPCs but it seems that it is not doing so
efficiently or else it is executing a DPC upon each schedule request by us
in a heavy load environment.
An alternative implementation which would …

NetKVM: TX: Drop heavy DPC scheduling

---

NetKVM/Common/Parandis_DesignPatterns.h
NetKVM/Common/ndis56common.h

The Add method should return the size of list after the element has been
added. This method will always return 0 when the list's typename is
CNonCountingObject.

 NetKVM: Observee: Make list countable

---

NetKVM/wlh/ParaNdis6-Driver.cpp

This reverts commit a79dae286ffc90fa6b97dd2b81b00679ab8f6401.
The reverted commit changes the msi vector assignment behavior, prior to
this
patch, Windows was assigning the vectors on his own even though in the
driver
code we attempted to assign it by ourselves. So this commit probably
revealed
that our assignment is not correct.
Let's try and understand how should we assign the vectors without causing
BSODs and then re-enable the commit.
This commit resolves BZ#1599631

Revert "NetKVM: Set AffinityPolicy to IrqPolicySpecifiedProcessors"

---

ivshmem/Device.c
ivshmem/Driver.h

This should fix this issue: https://github.com/virtio-win/kvm-guest-drivers-windows/issues/319
Signed-off-by: Lior Haim <lior@daynix.com>

[IVSHMEM] Use NonPagedPoolNx where appropriate

---

Balloon/app/blnsvr.props
Balloon/app/blnsvr.vcxproj
Balloon/app/device.cpp
Balloon/app/device.h
Balloon/app/service.cpp
Balloon/app/service.h
Balloon/app/stdafx.h

In order to support the ARM64 platform for Windows, the balloon service
is compiled for the "Universal" platform and must not use non-universal
APIs.

balloon: bz#1546821: use universal api in window 10 build

---

viocrypt/sys/viocrypt.inf

Sections [destinationdirs] and [sourcedisksfiles] are defined
multiple times, which leads to an error when building the drivers.
This commit fixes this by merging the sections into one, like [here](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/129/commits/3b4643859a65d2c9dcd22f46b9641e43f3da04ef).
Signed-off-by: Daniel Gonzalez Marx <daniel.gonzalezmarx@daynix.com>

viocrypt: Fix INF verification errors

---

NetKVM/Common/ParaNdis-AbstractPath.h
NetKVM/Common/ParaNdis-Common.cpp
NetKVM/Common/ParaNdis-SM.h
NetKVM/Common/ParaNdis-VirtQueue.h
NetKVM/Common/ndis56common.h
NetKVM/wlh/ParaNdis6-Driver.cpp
VirtIO/linux/virtio_config.h

In this batch of commits, support for VIRTIO_CONFIG_S_NEEDS_RESET  was added to the NetKVM driver.

support for VIRTIO_CONFIG_S_NEEDS_RESET to the NetKVM driver

---

NetKVM/Common/ParaNdis-CX.cpp
NetKVM/Common/ParaNdis-CX.h
NetKVM/Common/ParaNdis-Common.cpp
NetKVM/Common/ndis56common.h
NetKVM/wlh/ParaNdis6-Impl.cpp

This patch series address mainly the issues with CX interrupts that was originally reported in the following pull request:
https://github.com/virtio-win/kvm-guest-drivers-windows/pull/281

Fix possible race conditions with CX path.

---

NetKVM/Common/ParaNdis-Common.cpp

If power on procedure fails, it still must resume the
state machine, otherwise following pause flow never
completes.

netkvm: fix error flow on power on

---

NetKVM/Common/ParaNdis-VirtIO.cpp
NetKVM/Common/ParaNdis_LockFreeQueue.h
NetKVM/Common/ndis56common.h
NetKVM/wlh/ParaNdis6-Impl.cpp

Running SDV code analysis, 3 warnings were found.
2 warnings were fixed, 1 was supperesssed due to encapsulation that was not recognized by SDV tool.

Fixed SDV Code analysis warnings

---

NetKVM/wlh/ParaNdis6-Impl.cpp
viostor/virtio_stor.c

1: netkvm:  when qemu enable 8 queue (msi count is 17), nPathBundles is 2, qemu send msi large than 6, will result os crash.
2: viostor: same to netkvm,  vcpu 4, qemu hard queue 2, viostor  num_queues will be 1,  send msi 3 will result adpater->dpc null, os crash

netkvm and viostor: Proper do with enable msi.

---

viostor/virtio_stor.c
viostor/virtio_stor_hw_helper.c
viostor/virtio_stor_hw_helper.h

Fix the problem reviled by HLK scsicompliance VERIFY(10)(16) test and reported by Yan. If the  LBA  and the verification length exceeds the capacity of the medium, then the device server will return CHECK CONDITION status.

[viostor] handle VERIFY(16) requests properly

---

README.md

The Fedora URL in the README has been moved to a new server and now has a _much_ longer URL that wouldn't even remotely fit on a single line. So I ended up reformatting all four URLs as text links, with the URLs associated by reference (listed at the end of the README content).

README: Update Fedora docs URL; links by reference

---

viostor/virtio_stor.c
viostor/virtio_stor.h

Since virtio disks' vpds are same in pre-win10 os, different virtio disks have same
unique id. It affects some apps' behavior.
Signed-off-by: Zhou Wenjian <zhouwj.fi@gmail.com>

virtio-blk: set slot number to vpd

---

Balloon/sys/Device.c

BSOD occured during "Wdf - Kmdf Fault Injection Test" if driver was
built without USE_BALLOON_SERVICE defined.

balloon: bsod fix

---

VirtIO/WDF/Callbacks.c

Check the allocated pointer before filling the memory

virtio-wdf: Check for NULL

---

NetKVM/Common/ParaNdis-AbstractPath.h
NetKVM/Common/ParaNdis-CX.cpp
NetKVM/Common/ParaNdis-CX.h
NetKVM/Common/ParaNdis-Common.cpp
NetKVM/Common/ndis56common.h
NetKVM/wlh/ParaNdis6-Impl.cpp

https://bugzilla.redhat.com/show_bug.cgi?id=1666940
Set clear and simple rule for assignment of vectors to queues
and translation of MSIX messages to queues:
in case of one or two vectors they are assigned
to TX/RX queues and CX reuses the last vector. In this case
we do not spawn DPC for CX and process it during regular
RX/TX processing. For case of 3 and more vectors the processing
is the same as before.
Signed-off-by: Yuri Benditovich <yuri.benditovich@janustech.com>

netkvm: Fix functionality with single MSIX vector

---

status.txt

This commit is mostly to finalize transition to "upstream first" approach. 
In the past we used to use our internal repository as the primary one, 
backporting the changes to upstream. So, the records in "status.txt" log 
file were mostly related to our internal builds (even though that most of 
them are published at fedoraproject.org). During the transition some of 
tags were not beckported to upstream, as well as maintaining the status 
file was temporary discontinued. 
Now it 's time to add the missing log records back.

[virtio-win]. Update status file.

---

NetKVM/Common/ParaNdis-Common.cpp
NetKVM/Common/ndis56common.h
NetKVM/Common/virtio_net.h
NetKVM/wlh/ParaNdis6-Impl.cpp
NetKVM/wlh/ParaNdis6-Oid.cpp

Removed support for RSC implemented in private qemu patch.
Now the driver supports RSC according to the virtio spec
and upstream qemu code. The RSC feature is supported for
V1 device and for legacy device as well.

netkvm: RSC support according to virtio spec

---

NetKVM/Common/ParaNdis-CX.cpp

https://bugzilla.redhat.com/show_bug.cgi?id=1716248
Previous commit 2eea7a77b709f sets timeout on waiting
for response on control command. The command stops waiting
after 1,000 attempts to get the response with 1 microsecond
wait between attempts. The intention was to prevent infinite
wait in case of unexpected IOCTL after the miniport received
shutdown indication (note that NDIS should not call adapter's
callbacks after that, see
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ndis/nc-ndis-miniport_shutdown).
In this case the control queue is not initialized and
the QEMU does not receive the command and does not send
the response. But in case the limit is not sufficient and
the timeout happens during regular initialization flow and
QEMU does send the response, …

netkvm: Increase timeout of control command completion

---

NetKVM/netkvm.inx
NetKVM/netkvm_no_RSC.inx
NetKVM/netkvm_no_RSS.inx

This is an internal parameter, and it was removed from GUI as it might
confuse users. The parameter can still be added manually to registry.
Before the commit - default throttling limit value = 1000 , possible range: 1-10000
After the commit throttling limit value = 1000 (wasn't changed)
On < 6.20 (Win7 and below) it defines throttling limit.
On >= 6.20 (Win7 and above) it defines throttling limit if the limit provided
by OS is higher than this limit.
Signed-off-by: Basil Salman <basil@daynix.com>

[NetKVM] BZ#1745818 - Remove TestOnly.RXThrottle parameter from INF

---

NetKVM/CoInstaller/RegAccess.cpp

_tcsdup is a macro that eventually evaluates to _strdup or a similar
call, which uses malloc() to allocate the required memory. Such pointer
should be released using a call to free(), not operator delete.
Signed-off-by: Michał Janiszewski <janisozaur@gmail.com>

netkvm: Use free to deallocate memory allocated with malloc

---

NetKVM/Common/ParaNdis-RX.cpp

If you configure RX buffers on NetKVM level (inside Windows guest) to be 1024, but on qemu-kvm level it is set to 256, this may lead to connectivity loss once all RX buffers are exhausted. 
1. Create a Windows VM and configure `Init.MaxRxBuffers` to 1024;
2. Make sure on qemu-kvm side `rx_queue_size` is set to 256;
3. Generate from any other VM some traffic in bursts, e.g. by running `nuttcp`: 
a. Windows side: ` nuttcp.exe -S`
b. Linux side: `while (true) ; do nuttcp -l8972 -T1h -u -w4m -Ru -i1 <IP_of_Windows_VM> ; done`
**Note**: the issue can be reproduced only with rx_queue_size of 256 on qemu-kvm side and Init.MaxRxBuffers set to 1024 on NetKVM side. 
After a couple of seconds, VM loses network connectivity
It was found that in `netkvm!CParaNdisRX::Create` `m_nReusedRxBuffersLimit` …

Netkvm: m_nReusedRxBuffersLimit incorrectly set 

---

Balloon/sys/Device.c

https://bugzilla.redhat.com/show_bug.cgi?id=1553633
If on driver startup the ISR status is set, the driver
will not function properly as the ISR will not fire
anymore. At startup, after all the queues are prepared,
the driver shall process the ISR if it contains non-zero
value. This will also clear the ISR status and allow
further interrupts to come.

balloon: process the ISR status at startup

---

vioscsi/vioscsi.c
vioscsi/vioscsi.h
vioscsi/vioscsi.mof
vioscsi/vioscsidt.h

Please use the following .reg file to export "PhysicalBreaks" parameter to the Registry
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\vioscsi\Parameters\Device]
"PhysicalBreaks"=dword:000000ff

[vioscsi] introduce the Registry key to make number of physical breakes adjustable

---

Balloon/app/cleanAll.bat
NetKVM/clean.bat
pvpanic/clean.bat

ARM64 temp directory was not removed for NetKVM and Balloon
x64 temp directory was not removed for pvpanic

cleanup: Fix cleanup scripts to remove temp directories

---

virtio-win.sln

Someone accidentally turned off NetKVM Win8.1 Release build for x86.
I just turn it back on with this patch.

build: Reenable Win8.1 Release config for NetKVM

---

NetKVM/Common/ParaNdis_Common.cpp
NetKVM/Common/ParaNdis_Util.cpp
NetKVM/Common/ndis56common.h
NetKVM/wlh/ParaNdis6_Impl.cpp

NdisMAllocateSharedMemory maps memory as non cacheable on Arm Windows,
Given that Windows on Arm does not support unaligned accesses on uncached memory, this behavior does result in crashes.
As such, use MmAllocateContiguousMemorySpecifyCache for the Arm64 architecture.
This choice is safe. It's also to be noted that NdisMAllocateSharedMemory ignores the isCached attribute anyway.
With this fix, networking w/ netkvm for Windows on Arm works fine.
(tested with QEMU emulator version 5.0.50 (v5.0.0-1065-g9f1f264edb))

netkvm: Arm Windows support

---

NetKVM/Common/ParaNdis_Common.cpp
NetKVM/Common/ParaNdis_Util.cpp
NetKVM/wlh/ParaNdis6_Impl.cpp

NDIS Scatter-Gather DMA APIs are showing signs of old age and are becoming inefficient, especially on SoC systems. This driver should ultimately migrate from NDIS Scatter-Gather DMA APIs and move to either the WDF or WDM (HAL DMA v3) APIs as instructed here.
https://docs.microsoft.com/en-us/windows-hardware/drivers/network/ndis-scatter-gather-dma
This will result in a significantly improved performance, especially on SoC systems.
The migration process can be found here, by Jeffrey_Tippet_[MSFT], maitanier of these APIs in HAL by Microsoft:
https://community.osr.com/discussion/291413/getscattergatherlistex-and-ownership-lifetime-semantics
Meanwhile, the NDIS_SG_DMA_V3_HAL_API flag, added to NDIS_SG_DMA_DESCRIPTION::Flags allows unlocking a small portion of these benefits. One of such …

Instruct NDIS Scatter-Gather DMA stack to use HAL DMA v3 APIs when available (NDIS_SUPPORT_NDIS650)

---

NetKVM/Common/ParaNdis_Protocol.h
NetKVM/wlh/ParaNdis6_Driver.cpp

https://bugzilla.redhat.com/show_bug.cgi?id=1857045
In this flow the OS calls only DriverEntry and then
ParaNdis6_Unload.

netkvm: Free protocol resources in corner-case scenario

---

NetKVM/Common/ParaNdis_Common.cpp
NetKVM/netkvm-base.txt

*JamboPacket provides the same control over MTU.
The difference is that *JumboPacket includes ethernet header
size while the previous MTU does not.

nekvm: Use standard *JumboPacket instead of private MTU

---

viofs/pci/viofs.inf

Also renamed driver strings to avoid conflicts with the virtio-fs
user-mode service.

viofs-pci: rename driver name to match virtio-fs.

---

NetKVM/NotifyObject/utils.cpp

Add 14e4:16dc (NetXtreme-E Ethernet Virtual Function)
Signed-off-by: Annie Li <annie.li@oracle.com>

netkvm: notify object: add one Broadcom SRIOV adapter

---

viostor/virtio_stor.c
viostor/virtio_stor_hw_helper.c

For DISCARD operation correct disk's sectors into virtio units (512-byte)
and vice versa. For 4Kn virtual disks factor will be 8, for disks with
512-byte sector size factor will be 1.
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/513
Signed-off-by: Vitaliy Gusev <gusev.vitaliy@vstack.com>

viostor: 4Kn disk corruption after DISCARD/UNMAP

---

pvpanic/pvpanic/bugcheck.c
pvpanic/pvpanic/power.c
pvpanic/pvpanic/pvpanic.c
pvpanic/pvpanic/pvpanic.h

This patch set supports PVPANIC_CRASHLOADED in the pvpanic driver, and it contains 3 patches.
The 1/3 patch unifies the code style.
The 2/3 patch requires the patch posted for QEMU - https://lore.kernel.org/qemu-devel/1604346639-27090-1-git-send-email-alejandro.j.jimenez@oracle.com/
In Patch 3/3, when the crash dump is enabled in Windows guest, PVPANIC_CRASHLOADED will be triggered before the crash dump. It indicates a crash dump file will be generated in the guest. Otherwise, PVPANIC_PANICKED will be emitted. This means the guest crashes without a crash dump file created.

This PR set supports of PVPANIC_CRASHLOADED in the pvpanic driver

---

NetKVM/Common/ParaNdis_Common.cpp
VirtIO/WDF/VirtIOWdf.c
VirtIO/WDF/VirtIOWdf.h
VirtIO/linux/virtio_config.h
viofs/pci/power.c
vioscsi/helper.c
viostor/virtio_stor.c

According to virtio v1.1 spec: https://docs.oasis-open.org/virtio/virtio/v1.1/csprd01/virtio-v1.1-csprd01.html
VIRTIO_F_IOMMU_PLATFORM was renamed to VIRTIO_F_ACCESS_PLATFORM.
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1887843
Triggered by: https://lkml.org/lkml/2020/6/28/37
Signed-off-by: Basil Salman <Basil@daynix.com>
Signed-off-by: Basil Salman <bsalman@redhat.com>

VIRTIO_F_IOMMU_PLATFORM -> VIRTIO_F_ACCESS_PLATFORM

---

Balloon/sys/Device.c
Balloon/sys/ProtoTypes.h
Balloon/sys/balloon.c

https://bugzilla.redhat.com/show_bug.cgi?id=1828654
When the device was surprisingly removed the driver begins
removal flow and the host is not available. The driver
tries to report freed pages, each report takes 1 second
(timeout value), so the driver might not work for several
minutes. Skip reporting to host after surprise removal detected.

balloon: skip reporting to the host when it is not available

---

NetKVM/wlh/ParaNdis6_Oid.cpp

There is a small typo in NetKVM/wlh/ParaNdis6_Oid.cpp.
Should read `required` rather than `requred`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, requred -> required

---

viofs/svc/virtiofs.c

viofs-svc: fix a memory leak on RENAME2 requests

---

viogpu/viogpudo/viogpudo.cpp
viogpu/viogpudo/viogpudo.h
viogpu/viogpudo/viogpudo.inx

Temp solution for BZ#1918113. For some reason Win8 fails to allocate TranslatedResourceList
member of DXGK_DEVICE_INFO https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dispmprt/ns-dispmprt-_dxgk_device_info if MSISupported is enabled. Win10 seems to be working fine. I disable MSISupported for now. Going
to investigate this issue in the future.

[viogpu-dod] disable MSI interrupt in inf file.

---

viofs/svc/virtiofs.c

viofs-svc: fix a slash/backslash typo

---

viosock/inc/vio_sockets.h
viosock/sys/Device.c
viosock/sys/Socket.c
viosock/sys/public.h
viosock/viosocklib-test/viosocklib-test.c

The Viosock provider uses AF_VSOCK == 40 just because it was copied from Linux and does not conflict with the AFs currently defined for Windows. However, there may be conflicts with third party socket providers and in the future with new AF supported by Windows. Until MS adds AF_VSOCK to ws2def.h, the best solution would be to request the AF value from the viosock driver itself. At the moment, the driver returns a constant value of 40, dynamic calculation will be implemented later. See Viosocklib-test project to find out how to use sockets with dynamic AF.

Viosock: getting the AF value from the driver + fixes for couple of bugs

---

pvpanic/pvpanic/bugcheck.c
pvpanic/pvpanic/power.c
pvpanic/pvpanic/pvpanic.c
pvpanic/pvpanic/pvpanic.h

The following qemu patch advertises the 'PVPANIC_CRASHLOADED'
event,
https://lore.kernel.org/qemu-devel/20201109143311.1000958-1-pbonzini@redhat.com/
a custom set of supported events can be specified in the pvpanic
device command line options, e.g.:
-device pvpanic,events=<#>
The supported value of events is 1, 2 or 3, setting events value
other than these 3 values will cause Windows pvpanic driver failure.
Further restrictions of setting these values should be done in QEMU
side to avoid the failure in Windows pvpanic driver.
The pvpanic driver reads the property(events) supported by the
pvpanic device. When Windows guest crashes, the driver triggers
the following events based on the event value retrieved:
event   crashdump enabled        crashdump disabled
1    PVPANIC_PANICKED …

pvpanic: support pvpanic event properly

---

viorng/test/viorngtest.vcxproj

Use WDK toolset instead of SDK
Use 'LatestTargetPlatformVersion'
Remove unused statements

viorng: adapt viorng test to EWDK

---

vioserial/sys/Buffer.c

Especially from DMA write callback when this request is processing by QEMU.

[vioserial] Bugfix for BZ#1802466 There is no need in making write request cancelable

---

viogpu/viogpudo/viogpudo.cpp

Check if Frame Buffer pointer is valid before bit blitting.

bugfix for Bug 1918113 - Windows guest bsod with win8(q35) after install viogpudo driver

---

viostor/virtio_stor.c
viostor/virtio_stor.h

[viostor] bugfix for BZ#1979205 windows guest can not boot with indirect_desc=off

[viostor] bugfix for BZ#1979205  windows guest can not boot with indirect_desc=off

---

vioscsi/helper.c
vioscsi/vioscsi.c
vioscsi/vioscsi.h

The maximum block size has been increased to 512 pages and is now the same as Viostor's maximum block size. This can give io performance gains of up to 30% on fast storage. Dynamic memory allocation for sglist has been removed because the SRB extension now has enough pre-allocated space to hold the complete sglist. In addition, there was a bug in this code that led to unnecessary allocation and copying for requests of MAX_PHYS_SEGMENTS size, which also reduced performance.
We found that in some cases Vioscsi is up to 4 times slower than Viostore, setting the same number of max physical breaks (512) reduces this difference up to 2,5 times. :)
PS: Several months ago, @vrozenfe kindly suggested increasing the number of physical breaks to 512, but then it seemed unnecessary.

vioscsi: Increasing max phys breaks to 512

---

NetKVM/Common/ParaNdis_Common.cpp
NetKVM/netkvm-base.txt

NetKVM treats VLAN ID = 4095 as well as IDs from 1-4094, that is frames
with ID = 4095 pass and others don't. According to IEEE 802.1Q, 4095
can't be valid VLAN ID. Also, Win2022 HLK assumes that NDIS accepts
ID <= 4094.
Signed-off-by: Viktor Prutyanov <viktor.prutyanov@phystech.edu>

NetKVM: RHBZ#1979024: restrict max VLAN ID to 4094

---

NetKVM/netkvm-base.txt

Win2022 HLK (NICStrictPropertyValidation, Test-NetHLK) requires VlanID parameter size to be at least long.

NetKVM: RHBZ#1979024: change VlanID parameter type to long

---

viofs/svc/virtiofs.c

File's path should be null-terminated in the FixReparsePointAttributes
function as well.

viofs-svc: fix commit d297f841 (resolve links on path walkthough)

---

NetKVM/Common/ParaNdis_TX.cpp

It was noticed that as of build 20241 the sum of lengths of MDLs in NET_BUFFER
can be greater than the size of NET_BUFFER itself. As the result, the size of the
packet can be calculated incorrectly.
Instead of using the sum of MDLs lengths, we can cap the max length with the size
of NET_BUFFER.
Bug: https://github.com/virtio-win/kvm-guest-drivers-windows/issues/583
This PR is to also run HLK tests by CI.

NetKVM: Cap max length of the packet with NB size

---

Balloon/sys/balloon.inx

According to Microsoft Driver Security Guidance, access to the device object should be controlled by SDDL string.
Kernel-mode code and user-mode code running as System is allowed to open the device for any access with `"D:P(A;;GA;;;SY)"`:
```
SIDs:
[SY] - Local System Account
Rights:
[GA] - Generic All
```

Balloon: RHBZ#1826336: add security descriptor string

---

pvpanic/pvpanic/pvpanic.c
pvpanic/pvpanic/pvpanic.h
pvpanic/pvpanic/trace.h

First of all, according to Microsoft Driver Security Guidance driver shouldn't provide named device object (`\\.\PVPanicDevice`). Besides of that, no one uses PVPanic device in userspace. So, remove device object symbolic link.

PVPanic: RHBZ#1826336: revert "pvpanic: Add IOCTL_GET_CRASH_DUMP_HEADER"

---

fwcfg64/driver.c
fwcfg64/fwcfg.c
vioserial/sys/Buffer.c
vioserial/sys/Device.c
vioserial/sys/Port.c

FwCfg, VirtIOSerial:
* Replace ExAllocatePoolWithTag by ExAllocatePoolUninitialized
* Fix comparison of different types
* Fix uninitialized variable

Fix issues found by CodeQL

---

Balloon/sys/queue.c
vioserial/sys/Port.c

Fix two SDV issues marked as mustfix in Balloon and VirtIOSerial:    
- EvtIoStopCancel: 
- Requires EvtIoStop to unmark request cancellable
- EvtIoStopCompleteOrStopAck: 
- Requires EvIoStop to complete/cancel/postpone request
So, EvtIoStop handler
- Calls WdfRequestUnmarkCancelable for every request
- Calls WdfRequestStopAcknowledge/WdfRequestComplete for every request

Fix issues found by SDV in Balloon and VirtIOSerial

---

vioserial/sys/Buffer.c

Fix possible nullptr dereference in VIOSerialReclaimConsumedBuffers

Fix CodeAnalysis issues in VirtIOSerial

---

ivshmem/Device.c
vioinput/sys/Array.c
vioinput/sys/HidKeyboard.c
vioinput/sys/vioinput.h

This is another batch of fixes where ExAllocatePoolWithTag is replaced by ExAllocatePoolUninitialized

Fix CodeQL issues in VirtIOInput and Ivshmem

---

viofs/pci/ioctl.c
viofs/pci/power.c

In fact, commit [537a1ea](https://github.com/virtio-win/kvm-guest-drivers-windows/commit/537a1ea40441241945d1837bb0f6ea9b382f22cc) does partial suppression of SDV rule (InvalidReqAccess).
The rule ignores the fact that WdfRequestUnmarkCancelable is called only if WdfRequestMarkCancelableEx succeeded and Request is either Cancelled already or cancel is done by this call and checks branch `status == STATUS_NOT_SUPPORTED`.
It looks like problem described here [e8f5974a](https://github.com/virtio-win/kvm-guest-drivers-windows/commit/e8f5974a40d82d2f0924f71391263c04ff3a4623).

Fix CodeQL and SDV issues in VirtIOFS

---

NetKVM/Common/ParaNdis_TX.cpp

Current implementation of CParaNdisTX::BuildCancelList may trigger page fault and a bugcheck if m_SendQueue is already empty.
```
2: kd> !analyze -show
DRIVER_IRQL_NOT_LESS_OR_EQUAL (d1)
An attempt was made to access a pageable (or completely invalid) address at an
interrupt request level (IRQL) that is too high.  This is usually
caused by drivers using improper addresses.
If kernel debugger is available get stack backtrace.
Arguments:
Arg1: 0000000000000020, memory referenced
Arg2: 0000000000000002, IRQL
Arg3: 0000000000000000, value 0 = read operation, 1 = write operation
Arg4: fffff80eae479edf, address which referenced memory
```
Trap frame:
```
2: kd> .trap ffffcc81`1b5d2520
NOTE: The trap frame does not contain all registers.
Some register values may be zeroed or incorrect. …
```

NetKVM: Fix possible PF on ParaNdis6_CancelSendNetBufferLists path

---

vioscsi/vioscsi.c
vioscsi/vioscsi.h

regression introduced by commit c62a8a2c7bf73541fcfd6bc43bcf85147abf2620

[vioscsi] bugfix for BZ#1998473 windows guest can not boot with indirect_desc=off

---

Balloon/sys/memstat.c

warning C28170: The function 'StatInitializeWorkItem' has been declared to be
in a paged segment, but neither PAGED_CODE nor PAGED_CODE_LOCKED was found:
This warning is not emitted for functions that are __forceinline.
This warning makes Static Tools Logo Test to fail due to the warning marked as
'Must Fix'.
Signed-off-by: Sergey Bykov <sergey.bykov@nutanix.com>

balloon: fix C28170 warning for 'StatInitializeWorkItem'

---

NetKVM/Common/ParaNdis-RX.h
NetKVM/Common/ParaNdis-Util.h
NetKVM/Common/ParaNdis-VirtQueue.h
NetKVM/Common/ParaNdis_Protocol.cpp
NetKVM/Common/ethernetutils.h

Fix uninitialized class/structure members found by CodeAnalysis (C26495). Most of the warnings were produced by uninitialized `LIST_ENTRY m_ListEntry`. For now, all of C26495 warnings have gone.

NetKVM: fix uninitialized variables found by CodeAnalysis

---

NetKVM/netkvm-base.txt

Indicate that the driver is fully compatible with DMA remapping.
INF tested with 
* Windows HLK 2022 (InfVerifHLK.dll, 10.0.20348.1)
* Windows HLK 1607 (InfVerifHLK.dll, 10.0.14393.4)
* Windows HCK 2.1 (InfTest.exe, 6.3.9600.17298)

NetKVM: add DmaRemappingCompatible to INF

---

NetKVM/Common/DebugData.h
NetKVM/Common/ParaNdis-AbstractPath.h
NetKVM/Common/ParaNdis-RSS.h
NetKVM/Common/ParaNdis-SM.h
NetKVM/Common/ParaNdis-VirtQueue.h
NetKVM/Common/ParaNdis_Common.cpp
NetKVM/Common/ParaNdis_Protocol.cpp
NetKVM/Common/ParaNdis_RX.cpp
NetKVM/Common/ParaNdis_TX.cpp
NetKVM/Common/ParaNdis_VirtQueue.cpp
NetKVM/Common/ndis56common.h
NetKVM/Common/sw_offload.cpp
NetKVM/NetKVM-VS2015.vcxproj.filters
NetKVM/wlh/ParaNdis6_Driver.cpp
NetKVM/wlh/ParaNdis6_Impl.cpp
NetKVM/wlh/ParaNdis6_Oid.cpp
NetKVM/wlh/ParaNdis6_RSS.cpp

The driver still has CA warning 26812 in *.tmh files, generated by WPP.
There is no way to generate 'enum class' in *.tmh.

NetKVM: Use 'enum class' instead of 'enum' (CA warning 26812)

---

NetKVM/Common/sw_offload.cpp

IPv6 ESP header is treated as usual header(TCP, UDP etc.) by this change.
ESP header should not be treated like other extension headers.
Because it does not start with 'Next Header' field and next header is encrypted.
So base version of NetKVM drops IPv6 ESP(IPsec) packet as malformed packet.

NetKVM: Fix dropping IPv6 IPsec packets.

---

viofs/svc/virtiofs.c
viofs/svc/virtiofs.vcxproj

How to test:
* Use QMP commmand 
`{"execute":"device_add","arguments":{"driver":"vhost-user-fs-pci","id":"fs-pci1","bus":"pci.7","tag":"myfs","queue-size":"1024","chardev":"chr-vu-fs0"}}`
to add the device. A VirtIO-FS drive should appear in the guest.
* Use 
`{"execute":"device_del","arguments":{"id":"fs-pci1"}}` 
to delete the device. The drive should disappear and something like 
`{"timestamp": {"seconds": 1637196945, "microseconds": 957654}, "event": "DEVICE_DELETED", "data": {"path": "/machine/peripheral/fs-pci1/virtio-backend"}}`
`{"timestamp": {"seconds": 1637196946, "microseconds": 8101}, "event": "DEVICE_DELETED", "data": {"device": "fs-pci1", "path": "/machine/peripheral/fs-pci1"}}`
should be written to QMP.
* Device enable/disable in Device Manager should also work.

VirtIOFS: RHBZ#1996500: support device unplug/hotplug

---

vioscsi/helper.c
vioscsi/helper.h
vioscsi/trace.h
vioscsi/vioscsi.c
vioscsi/vioscsi.h

- the legacy pre-Win8 code has been removed
- fix for [Bug 2013976] Add bus reset handler to vioscsi driver

Vioscsi: code cleanup and lun reset hendler

---

vioscsi/vioscsi.c

Bugfix for Bug 2022656 - vioscsi:  Windows will fail to format a partition to NTFS with vioscsi+scsi-block
Please visit the following links for more information:
https://github.com/virtio-win/kvm-guest-drivers-windows/pull/502
https://github.com/virtio-win/kvm-guest-drivers-windows/pull/640
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/657

[vioscsi] limit NumberOfPhysicalBreaks and MaximumTransferLength according to max_sectors

---

viofs/svc/virtiofs.c

This patch fixes service fail at device removal. The problem was introduced in [6dd7cd8d](https://github.com/virtio-win/kvm-guest-drivers-windows/commit/6dd7cd8d88227a788af847b64f97c7900b287b2e).

VirtIOFS: fix pointer dereference in CloseDeviceInterface call

---

fwcfg64/driver.c
fwcfg64/driver.h

We cannot rely on KeCapturePersistentThreadState when passing uninitialized buffer.

FWCfg64: RHBZ#2035659: zero minidump buffer and check output

---

viofs/svc/virtiofs.cpp

`FspPosixDeletePath(fullpath)` shouldn't be called until last use of `filename` because it points to the same buffer.

VirtIOFS: fix use-after-free in Create handler

---

vioscsi/helper.c

A handful of the log statements in GetScsiConfig are incorrect, this patch
fixes event_info_size and sense_size outputs.
Signed-off-by: Jon Kohler <jon@nutanix.com>

vioscsi: trivial dbg log update in GetScsiConfig

---

Tools/build.bat

build.bat will build the entire solution set one by one, which is single
threaded. On multi-processor builders in a CI/CD system, this is a bit
sluggish.
Enable msbuild -maxCpuCount on all msbuild commands, which will parallelize
msbuild actions where possible.
On an Azure Standard_DS2_v2 (i.e. a 2 vcpu builder) this change reduces
build_AllNoSdv.bat time from 12 min to 8 min.
Also, fix minor nit in top of file comments to reflect supported build targets,
which removes Win7, adds Win8.1.
Signed-off-by: Jon Kohler <jon@nutanix.com>

build: enable msbuild maxCpuCount

---

vioscsi/helper.c
vioscsi/vioscsi.c

vioscsi: fix MaximumTransferLength off-by-one and max_sectors handling
This change fixes MaximumTransferLength and max_sectors handling as
described in #498 and #735.
- Changed initialization of seg_max to SCSI_MINIMUM_PHYSICAL_BREAKS. This
gets immediately overwritten anyways; however, this seems like the most
sane value to initialize this to, rather than MAX_PHYS_SEGMENTS.
- Squashed adaptExt->dump_mode branching into one set of if/then, which allows
for adaptExt->indirect to be set immediately before it is evaluated.
- Moved adaptExt->indirect configuration to GetScsiConfig.
- Readded initialization of ConfigInfo->MaximumTransferLength to
SP_UNINITIALIZED_VALUE. This immediately gets overwritten; however, it
makes it clear what the starting point is (unlimited) so that we can …

vioscsi: fix MaximumTransferLength off-by-one and max_sectors handling

---

NetKVM/wlh/ParaNdis6_RSS.cpp

This PR is to run HLK tests against the changed binary
It was noticed that if RSS is configured on the client
in Conservative profile, Windows will/may issue
OID_GEN_RECEIVE_SCALE_PARAMETERS OID to update RSS
Parameters. However, RSSScalingSettings.CPUIndexMapping
is nullified in the initial call.
Bug: https://github.com/virtio-win/kvm-guest-drivers-windows/issues/730

NetKVM: Do not touch RSSParameters unless requested

---

viofs/pci/ioctl.c
viofs/pci/isrdpc.c
viofs/pci/power.c
viofs/pci/viofs.c
viofs/pci/viofs.h
viofs/pci/viofs.inf

Before this patch all FUSE requests were made through 'hiprio' VQ.
To conform VirtIO specification, only FUSE_FORGET, FUSE_BATCH_FORGET, FUSE_INTERRUPT are submitted to 'hiprio' VQ. Other FUSE messages are submitted to first 'request' VQ.
The rest of 'request' VQs are still unused, but may be utilized in future:
- MessageNumber = 0 corresponds to 'hiprio' VQ
- MessageNumber = 1 corresponds to all of the 'request' VQs (although only one is used for now)

RHBZ#2062572: use 'hiprio' VQ for FORGET/BATCH_FORGET/INTERRUPT only

---

viofs/svc/virtiofs.cpp

Flags O_RDWR and O_WRONLY along with O_DIRECTORY cause EISDIR on the host during open(...). Actually, there is no need to involve write access when performing Create/Open of a directory. So, pass just O_RDONLY.

RHBZ#2063722: don't set O_RDWR/O_WRONLY as flags for FUSE_OPENDIR

---

viofs/svc/virtiofs.cpp

During WinAPI `CreateDirectory` handling WinFSP submits `Create` and then `Close` operations to the service.
So, `Create` handler must open the directory to avoid `Close` of invalid file handle.

VirtIOFS: RHBZ#2065481: open directory on Create

---

viofs/svc/virtiofs.cpp

Host buffer size is limited, so FUSE_READ buffer must be also limited.
FUSE_INIT output has `max_pages` field (FUSE_MAX_PAGES flag) which can be used to set max buffer size.

VirtIOFS: RHBZ#2024518: limit FUSE_READ out buffer size by max_pages

---

viostor/virtio_stor.c
viostor/virtio_stor_hw_helper.c

Reported-by: icessspark
for the problem description please visit 
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/692
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/578
and
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/747

adjust the maximum transfer lenght if VIRTIO_BLK_F_SEG_MAX flag is on

---

NetKVM/Common/ParaNdis_TX.cpp

https://bugzilla.redhat.com/show_bug.cgi?id=2067167
https://bugzilla.redhat.com/show_bug.cgi?id=2063594
This reverts commit 5fcd9ea620559e440ba4841b3a190fa6f9a22f15.
Mentioned commit was intended to solve the problem
https://bugzilla.redhat.com/show_bug.cgi?id=1972487
But during later tests it was found that the commit has triggered
other problems in perf6 and mpe tests
We revert the commit and continue the investigation

Revert "netkvm: do not complete packets in sending path"

---

viofs/svc/fusereq.h
viofs/svc/virtiofs.cpp

Now service can be stopped by Service Manager, because it handles `SERVICE_CONTROL_STOP` and `SERVICE_CONTROL_SHUTDOWN`.
Besides of that, the service submits `FUSE_DESTROY` request to end FUSE session at service stop and device remove.

RHBZ#2075862: VirtIO-FS: make the service stoppable

---

viostor/virtio_stor.c

On windows, we can use wmic.exe to retrieve disk serial number, full
command line is "wmic path win32_physicalmedia get serialNumber".
The command will random fail if driver returns SRB_STATUS_SUCCESS for
unsupport control codes. (In this case, the ctlcodes are SMART_GET_VERSION,
SMART_SEND_DRIVE_COMMAND, SMART_RCV_DRIVE_DATA, currently none of them
are supported by viostor)
"wmic path win32_physicalmedia get serialNumber" works as follow:
1. Call DeviceIOControlFile with SMART related ioctl codes;
2. If ioctl succeeded, parse ioctl buffer to check smart version and
get serial number. (The driver returns SRB_STATUS_SUCCESS for these
ioctl codes, but doesn't fill the output buffer with correct SAMRT data,
so the output buffer contains random bytes, when caller trying to parse
data in …

[viostor] don't return SRB_STATUS_SUCCESS for unsupported control codes

---

viofs/pci/ioctl.c
viofs/pci/power.c
viofs/pci/viofs.h

Typical large VirtIO-FS request is 1MiB + 2 pages, which is too much for default queue-size=128. Use of 2 pages indirect area allows to process request of up to 2MiB.

VirtIO-FS: use indirect VirtIO descriptors for large SG-lists

---

vioscsi/vioscsi.c
vioscsi/vioscsi.h
viostor/virtio_stor.c
viostor/virtio_stor.h

The memory buffer length viostor allocates to store the group
affinity mask is based on the num_queues but the last redirection
message number is based on msix_vectors. If msix_vectors is greater
than num_queues, storport will write beyond the end of the allocated
buffer which causes non-paged pool corruption. This change fixes
the explained problem.
1. Set last redirection message number based on num_queues in viostor.
2. Add a field num_affinity in ADAPTER_EXTENSION to store the group
affinity array length.
3. Add assertion in vioscsi and viostor to ensure that last redirection
message number is less than num_affinity.
Signed-off-by: Hao Xiang <hao.xiang@bytedance.com>

Fix buffer overrun in viostor when VM is configured to have more disk queues than number of CPUs.

---

viofs/svc/virtiofs.cpp

Allow every user in guest system act like files and folders owner.
Remove session change handling and UID/GID change logic.

RHBZ#2112559: VirtIO-FS: set guest side owner UID/GID to Everyone

---

viogpu/viogpudo/viogpudo.inx

This patch customizes the viogpudo INF file, so it can be configured
by customized Subsystem Vendor ID and device naming for various vendors.
The macros related to the customization are the following,
_INX_SUBSYS_VENDOR_ID
INX_PREFIX_VENDOR
INX_COMPANY
Signed-off-by: Annie Li <annie.li@oracle.com>
Reviewed-by: Darren Kenny <darren.kenny@oracle.com>

[viogpudo] Customize the INF file

---

viofs/svc/virtiofs.cpp

In `e3e722c` both owner and group on guest side were set to `Everyone`. But when converting POSIX mode to Windows security descriptor WinFSP can restrict owner's rights to group's rights if owner's rights are more permissive. Thereby, some previosly working configurations (e.g. shared directory with `0700` rights) were broken. So, evelate group rights when converting to security descriptor.

RHBZ#2112559: VirtIO-FS: align group rights to owner rights

---

viofs/LICENSE
viofs/pci/LICENSE
viofs/svc/LICENSE

Add the BSD license and WinFSP license that is used by the virtio-fs
service.

virtio-fs: BZ#2119336: Add LICENSE file to viofs driver

---

viostor/virtio_stor.c

Bug 2020998 - [virtio-win] Windows 10 "Optimize drive"/Trim/Discard causes all data to be rewritten

[viostor] fix vpd 0xb0 Optimal Unmap Granularity report

---

viosock/sys/Rx.c

The `VIOSockReadDequeueCb` routine is responsible for removing requests from socket's Read queue and their processing (e.g. filling their buffers with incoming data and completing them). At most one instance of this routine can be running at a time, which is ensured by interlocked operations on the `lInProgress` variable. However, not all return paths were covered -- if the Read queue was empty, the routine would just return without unlocking the variable. Such behavior pretty much ruins chance of getting the recv() call right.
This fix unlocks the `lInProgress` also on this forgotten return path, inlucing emission of a trace event.

VIOSOCK: Fix VIOSockReadDequeueCb

---

viofs/svc/utils.h
viofs/svc/virtiofs.cpp
viofs/svc/virtiofs.vcxproj

When `LOOKUP` or `UNLINK`/`RMDIR` or `RENAME`/`RENAME2` request is required, the service tries to send it with exact filename (as usual). If the request result is not success, the service sends `OPEN` and `READDIR` requests to parent directory and tries to find target name among parent directory entries by case-insensitive comparisons and perform `LOOKUP`/`UNLINK`/`RMDIR`/`RENAME`/`RENAME2` on it and then `RELEASE` parent directory.
Add `-i` option and registry key `CaseInsensitive`.
Example:
```
$ ls Z:\
Hello.txt  Привет.txt
$ cat HELLO.txt
Hello
$ cat ПРИВЕТ.txt
Привет
```

VirtIO-FS: initial case insensitive support

---

viostor/virtio_stor_hw_helper.c

if QEMU discard_granularity parameter not specified

[viostor] set discard sector alignment equal to 8 sectors (4K) 

---

viosock/wsk/provider.c
viosock/wsk/viowsk.c

ExAllocatePoolWithTag has been deprecated in Windows 10 version 2004. Starting with EWDK 11 22H2, using ExAllocatePoolWithTag causes a warning, which is treated as an error.
EWDK suggests replacing ExAllocatePoolWithTag on ExAllocatePool2, but ExAllocatePool2 only works on Windows 10 2004 and above. This commit replaced this function with ExAllocatePoolUninitialized to support Windows 10 2004 and below.
All of these features first appeared in WDK 2004.
Fixes for https://bugzilla.redhat.com/show_bug.cgi?id=2138115

viosock: Fix compilation warning in EWDK11 22H2

---

viogpu/common/baseobj.cpp
viogpu/common/viogpu_pci.cpp

ExAllocatePoolWithTag has been deprecated in Windows 10 version 2004. Starting with EWDK 11 22H2, using ExAllocatePoolWithTag causes a warning, which is treated as an error.
EWDK suggests replacing ExAllocatePoolWithTag on ExAllocatePool2, but ExAllocatePool2 only works on Windows 10 2004 and above. This commit replaced this function with ExAllocatePoolUninitialized to support Windows 10 2004 and below.
All of these features first appeared in WDK 2004.
Fixes for https://bugzilla.redhat.com/show_bug.cgi?id=2138115

viogpu: Fix compilation warning in EWDK11 22H2

---

VirtIO/WDF/Callbacks.c
VirtIO/WDF/Dma.c
VirtIO/WDF/PCI.c

ExAllocatePoolWithTag has been deprecated in Windows 10 version 2004. Starting with EWDK 11 22H2, using ExAllocatePoolWithTag causes a warning, which is treated as an error.
EWDK suggests replacing ExAllocatePoolWithTag on ExAllocatePool2, but ExAllocatePool2 only works on Windows 10 2004 and above. This commit replaced this function with ExAllocatePoolUninitialized to support Windows 10 2004 and below.
All of these features first appeared in WDK 2004.
Fixes for https://bugzilla.redhat.com/show_bug.cgi?id=2138115

virtio: Fix compilation warning in EWDK11 22H2

---

viostor/virtio_stor.h
viostor/virtio_stor_hw_helper.c

[Bug 2020998] Windows 10 "Optimize drive"/Trim/Discard causes all data to be rewritten

[viostor] make sure that discard sector alignment is 8 sectors (4K) mnimum

---

viofs/svc/virtiofs.cpp

For example, FUSE_OPEN may return -EACCES. Previously, it was returning "Catastrophic failure". Now it will return "Access Denied" as follows:

VirtIO-FS: handle EACCES as FUSE request output

---

README.md

Current drivers are built using EWDK 11, have the readme point to that build process.
Signed-off-by: Alexander Balderson [mr.balderson.alex@gmail.com](mailto:mr.balderson.alex@gmail.com)

Update Readme to point at latest build steps

---

buildAll.bat
vioinput/hidpassthrough/hidpassthrough.vcxproj

- resolves: 
BZ#2012756 - [virtio-win][vioinput]Signtool verify viohidkmdf.sys file failed with virtio-win-prewhql-211 on win10+ guests
BZ#2141603 - HCK-CI failed to install virtio-input driver

vioinput: Fix catalog file generation

---

fwcfg64/driver.c

[fwcfg64] fix for Bug 2138303 - fwcfg driver can not be disabled

---

viosock/inc/vio_sockets.h
viosock/sys/Socket.c

The Socket driver enables its users to set several socket options, however, their values are not defined in kernel mode (winsock2.h defines them for usermode code). This commit moves these definitions from internal source file of the Socket driver into its public header file.
I would be happy if this PR can be merged before #835 since I am using one of the published socket options in a test driver there.

viosock: Publish supported socket options also for the kernel

---

viofs/svc/virtiofs.cpp

Previously, the virtiofs.exe was exiting silently.

RHBZ#2149547: print error message if failed to load WinFsp

---

viofs/svc/virtiofs.cpp

Fix warning `C4244`: `=`: conversion from `uint64_t` to `int`, possible loss of data.

VirtIO-FS: fix uint64_t to int conversion in UnixTimeToFileTime

---

VirtIO/WDF/Dma.c

* Fix warning `C6387`: `ctx->buffer` could be `0`: this does not adhere to the specification for the function `WdfDmaTransactionInitialize`.
* Fix warning `C6386`: Buffer overrun while writing to `p`: the writable size is `allocSize` bytes, but `72` bytes might be written

VirtIO-WDF: Dma: fix CodeAnalysis warnings

---

viofs/svc/utils.h
viofs/svc/virtiofs.cpp

By default, host owner UID:GID is set to UID:GID of shared directory owner. New command-line argument `-o` and registry parameter `Owner` override this behavior. A valid parameter value looks like `1234:5678`.

RHBZ#2174170: VirtIO-FS: introduce host owner UID:GID parameter

---

fwcfg64/power.c

Previously, fwcfg64 driver was failing if fw_cfg device was present, but `etc/vmcoreinfo` entry wasn't. The driver shouldn't fail when device is OK. Anyway, `dump-guest-memory -w` will not work without vmcoreinfo.

RHBZ#2177673: fwcfg64: don't fail if unable to work with vmcoreinfo

---

viofs/svc/virtiofs.cpp

The `fallocate` call is Linux-specific and some host filesystems don't support some of its arguments. NFS doesn't support `FALLOC_FL_KEEP_SIZE` which is helpful when `AllocationSize` > 0 in `Create`. Since we can't determine host FS from the guest side, ignore `fallocate` failure. We will get an error anyway during a further `Write`, if there isn't enough space.

RHBZ#2183941: ignore FUSE_FALLOCATE failure in Create

---

viostor/virtio_stor.c
viostor/virtio_stor.h

If user hot plugs a vioblk device and then hot plugs vcpus, the guest hangs after vcpus have been hot plugged.
vioblk hot plug:
drive_add auto file=test.img,format=raw,if=none,id=test1,cache=none device_add virtio-blk-pci,drive=test1,id=test-disk,bus=pciroot2
vcpu hot plug:
device_add host-x86_64-cpu,socket-id=16,core-id=0,thread-id=0,id=cpu16 device_add host-x86_64-cpu,socket-id=17,core-id=0,thread-id=0,id=cpu17 device_add host-x86_64-cpu,socket-id=18,core-id=0,thread-id=0,id=cpu18 device_add host-x86_64-cpu,socket-id=19,core-id=0,thread-id=0,id=cpu19
This hang issue is a regression caused by following commit, commit 65589a2d4dbf7844a3f363e78b1837fe4a1136c5
[viostor] report SRB_STATUS_NO_DEVICE status on removed virtio-blk HBA Reporting status on the removed virtio-blk HBA is fine, but …

viostor: Fix guest hang issue caused by hot plugging vioblk and vcpus

---

vioscsi/helper.c

It was noticed that if a VQ gets exhausted, completing a request with SRB_STATUS_BUSY only will result in stalling of a whole unit and it may lead to the performance degradation during IO intensive workloads. The issue is mostly seen when there is a high number of outstanding IOs, e.g. ~512 or more. This behaviour was introduced with the commit https://github.com/virtio-win/kvm-guest-drivers-windows/commit/f1338bb7edd712bb9c3cf9c9b122e60a3f518408. 
Instead of stalling the unit, it is better to report device-busy by setting SCSISTAT_QUEUE_FULL in ScsiStatus  of a SRB. In that case StorPort pauses the logical unit queue and waits until a certain amount I/O requests are completed by the miniport before sending any further requests. 
The test case is simple:
1. Create a VM with 2 vCPUs.
2. …

vioscsi: set SCSISTAT_QUEUE_FULL if a buffer cannot be added to a VQ

---

viosock/lib/native.c
viosock/sys/Device.c
viosock/sys/Rx.c
viosock/sys/Socket.c
viosock/sys/Tx.c

The problem (or "problem") with `STATUS_TIMEOUT` is that it is classified as a success status code (the `NT_SUCCESS` macro returns `TRUE`). This problem does not appear in user mode since `viosocklib` converts `STATUS_TIMEOUT` to corresponding Win32 error code,
However, kernel mode components/drivers mostly use `NT_SUCCESS` macro to distinguish success from failure, thus, `STATUS_TIMEOUT` can be misleading for them. Also, some uses of the `VIOSockPendedRequestSetEx` in the viosock driver itself improperly handle `STATUS_TIMEOUT`.
This pull request modifies viosock driver to return `STATUS_IO_TIMEOUT` instead. This is an error code. `viosocklib` is also updated to translate this code to the timeout Win32 error.

viosock: Use STATUS_IO_TIMEOUT instead of STATUS_TIMEOUT

---

viostor/virtio_stor.c
viostor/virtio_stor_hw_helper.c

Fix for https://bugzilla.redhat.com/show_bug.cgi?id=2133261
Win11 22H2 can perform only quick format on a thinly provisioning volume.
Windows can recognize such volume by checking ProvisioningType == PROVISIONING_TYPE_THIN
reported in VPD_LOGICAL_BLOCK_PROVISIONING VPD. in case of virtio-scsi the ProvisioningType
can be changed from PROVISIONING_TYPE_THIN to PROVISIONING_TYPE_RESOURCE by setting discard_granularity to 0.
Previously virtio-blk driver was setting  ProvisioningType based on discard type but not on discard_granularity value, which 
was different from virtio-scsi.

set ProvisioningType in LOGICAL_BLOCK_PROVISIONING VPD according discard_granularity size

---

NetKVM/NotifyObject/notifyobject.vcxproj

Earlier commit 42b1e51e227 has changed the configuration of ProtocolService from Release to Win10Release but did not it in the postbuild of NotifyObject. Fixing it

notyfyobj: Fix targets

---

viosock/sys/Rx.c
viosock/sys/Socket.c
viosock/sys/viosock.h

This routine is used to match send() and recv() operations made on a given socket. This occurs in these situations:
- after a send() is recorded for the socket,
- when a new recv() request is added to an empty queue of such requests,
The routine may requeue a recv() request (e.g. because it finds not enough send() ones to fully satisfy it), which may trigger it being called recursively again and again. Thus, a mechanism to detect the recursion is implemented through the lInProgress variable. However, this may backfire in some rare cases, for example:
- the routine is called after recording a send() request, it is about to exit since the recv() queue is empty, simultaneously
- a recv() request just got into the queue, however, VIOSockReadDequeueCb does not do the matching since another …

viosock: Fix rare race condition in VIOSockReadDequeueCb

---

NetKVM/CoInstaller/NetKVMnetsh.cpp
NetKVM/CoInstaller/netkvmco-vs2015.vcxproj
NetKVM/CoInstaller/stdafx.h

https://bugzilla.redhat.com/show_bug.cgi?id=2130768 Win11 22h2 WDK changed the definition of CMD_ENTRY without flexibility or backward compatibility.
Until we discard the netkvmco.dll and move its
functionality to another executable, we support both variants and distinguish win11 22h2 by file version of netsh.exe.

netkvmco: quick and dirty support for win11 22h2

---

viofs/svc/utils.h
viofs/svc/virtiofs.cpp

Case-insensitive file system should lower `FILE_CASE_SENSITIVE_SEARCH` flag in `FILE_FS_ATTRIBUTE_INFORMATION`. Along with `FILE_CASE_PRESERVED_NAMES` it means for Windows that the FS knows the correct case, but lookups can be case-insensitive.
Also, fix `MoveFile("FILE", "file", 0)` failure caused by this change.

RHBZ#2172002: set CaseSensitiveSearch depending on -i argument

---

vioscsi/vioscsi.c

Let's free the buffer even if the call to `StorPortRegistryRead` fails.

vioscsi: Fix a memory leak in VioScsiReadRegistryParameter

---

viosock/sys/Device.c

When select called to poll events of vsock socket, there is a large chance of failure with WSAEINVAL code, especially with timeout param. The trace events gives "Invalid output len" output, which help us to find this bug, that IOCTL_SELECT should always return with correct 'BytesReturned' in success.

viosock: select IO control should return with 'Information' in success

---

viosock/sys/Rx.c

This patch fixs one bug, that multiple recv calls always return the same data. From upper layer, it seems like Stream data pointer never moves. One simple multiple-recvs test case can reproduce this easily.

viosock: fix one fatal recv data error bug

---

viosock/sys/Socket.c

There are two obvious variable asignment errors 
in vio socket acception context, fix it.

viosock: fix two obvious code errors

---

viosock/sys/Rx.c

Assign the corresponding RxCb's attribute to zero only after it is not used, otherwise some computational errors may cause unexpected behivor.

viosock: make sure to get a correct computation

---

vioscsi/helper.c
vioscsi/trace.h
vioscsi/utils.c
vioscsi/vioscsi.c

This PR is consist of two cosmetic logging improvements:
1. The first one is to slightly change the wording to reflect the current code and make it more comprehensive. Extended the list of SCSI Ops.
2. The second one is to improve SRB tracing with INFORMATION logging level to reduce the noise from ENTER/LEAVE functions (that is logged with VERBSOE level). With this change we start logging SRB info for `VioScsiBuildIo`, `SendSRB` and `HandleResponse` calls. Also extended the list of SCSI Ops from EWDK2022. 
It is the way the log looks like:
```
[0]0004.01D0::08/06/2023-11:18:36.954 [vioscsi.sys] VioScsiBuildIo <--> Operation SCSIOP_PERSISTENT_RESERVE_IN (0x5E), Target (0::0::2), SRB 0xFFFFCE0C44852980
[0]0004.01D0::08/06/2023-11:18:36.954 [vioscsi.sys] SendSRB <--> Operation …
```

vioscsi: logging improvements for SRB tracing

---

viosock/lib/viosocklib.c

VIOSockTimerStart() already contains a minux symbol, using an extra minux in VIOSockSelect() is needless.

viosock: remove an extra minus in select timeout computation

---

viosock/sys/Rx.c
viosock/sys/Socket.c
viosock/sys/viosock.h

using traceview to see tracing events, it turns out the windows thread id handle returned by PsGetCurrentThreadId() is really an integer, this means a NULL handle can be equal to a zero value thread ID(handle is 0), thus cause one infinit wait live lock issue which I actually encounters. Anyway, use a non-positive integer value than this handle seems to be safer.

viosock: fix one live lock issue

---

viosock/sys/Rx.c

We should set pCurrentCb->BytesToRead to 0 before calling VIOSockRxCbPushLocked(). Consider following scenario:
1. thread 1 calls VIOSockRxCbPushLocked(), add CurrentCb to RxCbBuffers
2. thread 2 calls VIOSockRxPktInsert(), get the CurrentCb from RxCbBuffers, and uses virtqueue_add_buf() to add the CurrentCb to RxVq
3. thread 2 calls VIOSockRxVqProcess(), get the CurrentCb from virtqueue_get_buf(), and ready to be read from user recv() call
4. thread 1 sets pCurrentCb->BytesToRead to 0, so it modifies the CurrentCb used by thread 2

viosock: fix CurrentCb BytesToRead setting

---

vioscsi/vioscsi.c

We discovered recently that CompletePendingRequests has a flaw when it completes pending paging write IO requests. 
Here are the repro steps that 100% trigger the problem in our lab:
1. Start intensive IO write operations inside the guest.
2. Configure backend storage to *delay* all IO requests for more than 60 seconds. 
3. Wait until the guest gets frozen. 
4. Configure storage not to delay new IOs. 
5. Wait until storport invokes reset handler and vioscsi completes pending SRBs. 
6. Once the backend storage completes IO requests that were delayed, you will get the guest crashing with 0x1A bugcheck. 
```
kd> !analyze -show
MEMORY_MANAGEMENT (1a)
Arguments:
Arg1: 000000000000003f, An inpage operation failed with a CRC error. Parameter 2 contains
the pagefile offset. Parameter 3 contains …
```

vioscsi: add DeviceReset on CompletePendingRequests path

---

viosock/sys/Tx.c

If the first element in SgList is not 4KB, there will be 17 element in SgList for 64KB data, which will cause a stack buffer overrun BSOD. This issue can be reproduced by sending more then 64KB data in one send().
From #957 
> For the TX fix, it is a bad practice to allocate memory on stack for SG in any case. I suggest to make a real fix that will allocate memory properly (also with consideration of probable usage of IOMMU) and not workaround.
SG is only used to pass addr and length to virtqueue_add(), so I don't understand why it's a bad practice to allocate memory on stack for SG. I also checked other virtio drivers and found some of them use stack memory as well.

viosock: fix sending large packet sg list

---

viosock/lib/native.c

Wait on a Event instead of the socket itself after calling NtWriteFile()/NtReadFile(), otherwise WaitForSingleObject() may return before the write/read completes, thus returning wrong status to caller. This issue can be reproduced by having a sender thread and a receiver thread running on a socket at the same time, and sometimes send() may return 0 bytes sent, even though the other side can receive the packet.

viosock: fix NtReadFile/NtWriteFile

---

vioscsi/vioscsi.c
vioscsi/vioscsi.h

We have seen many cases where we see vioscsi 129 reset events leading to a complete guest hang. While overall reset logic added in https://github.com/virtio-win/kvm-guest-drivers-windows/pull/684 likely mitigates the problem, we still see sporadic requests from customer where they see guest OSes hangs.
This change will make it possible configure system to bugcheck and get a memory dump and the state of the VQs.
By default, the behaviour will remain intact - complete pending SRBs, but can be changed to either to do nothing or bugcheck the guest by setting the registry value.
```
Path:    HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\vioscsi\Parameters
Name:    VioscsiActionOnReset
Type:    REG_DWORD
Values:
0x0 - Complete all pending SRBs (default)
0x1 - Do nothing (all unserved …
```

vioscsi: add logic to make reset mechanism configurable

---

viogpu/viogpudo/viogpudo.cpp

This PR deals with the situation when the DXGKRNL_INTERFACE passed to VioGpuDod::StartDevice is larger than driver's place for such structure, represented by the m_DxgkInterface attribute. In such a case, the driver just degrades the structure to the largest it can handle. This should be fine since DXGKRNL_INTERFACE only adds new members when advancing to its new versions.
Fixes: #967

viogpu: Cope with larger than expected DXGKRNL_INTERFACE size

---

vioserial/sys/Control.c
vioserial/sys/Device.c
vioserial/sys/Port.c
vioserial/sys/vioser.h

This PR prevents the VirtIO Serial Driver from potentially infinitely waiting for the hypervisor when switching to the `WdfPowerDeviceD3Final` power state (that happens when the system is being shut down, or the device is being removed). In such case, the `XxxEvtDeviceD0Exit` callback routine must complete within certain time interval. That is achieved by enhancing `VIOSerialSendCtrlMsg` with an extra parameter determining whether long waits are possible.

Vioser: Do not wait infinitely when power down or removal is imminent

---

viosock/sys/Socket.c
viosock/sys/viosock.h

Spin locks are operated at IRQL >= `DISPATCH_LEVEL`, thus, such code must not be paged. Otherwise, it can be paged out during its execution which provides the user with a `IRQL_NOT_LESS_OR_EQUAL` bug check. Virtio Socket driver wraps some of its spinlock usage into several inline functions:
- `VIOSockPendedRequestSetLocked`,
- `VIOSockPendedRequestSetResumeLocked`,
- `VIOSockPendedRequestGetLocked`.
However, these functions are than called from routines marked as pageable code which can trigger the bug check. This commit makes the functions not inline, thus, making them reside in nonpaged memory.

viosock: Do not inline functions working with spinlocks to paged code

---

vioserial/sys/Port.c

In some scenario such as suspend the guest, the host will notify connect close, but the status can not be sync to guest driver,
which will cause a bug while the guest write the seiral before the host connect happend. so it's better just let the connection status to be false rather then true. because the next boot(resume) will enable the connection again

vioserial : host connection status set to false when driver exit

---

viofs/pci/viofs.c

Resolves: https://issues.redhat.com/browse/RHEL-19069
Resolves: https://github.com/virtio-win/kvm-guest-drivers-windows/issues/1004
Remarks from https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-mmallocatepagesformdlex
The caller must use MmFreePagesFromMdl to release the memory pages that are described by an MDL that was created by MmAllocatePagesForMdlEx. After calling MmFreePagesFromMdl, the caller must also call ExFreePool to release the memory that is allocated for the MDL structure.

[viofs] Fix MDL structure memory leak

---

NetKVM/Common/ParaNdis_Common.cpp
NetKVM/Common/ParaNdis_RX.cpp

https://issues.redhat.com/browse/RHEL-20575
Currently the driver get RX descriptor from the rx virtQ, analyses it (L2/L3), calculates hash and delivers to the proper RSS queue. Later it extract the packet from the RSS queue and checks whether it passes RX filters.
Now we move the filtering to the earliest stage - just after basic analysis.
Note that in case of vhost there are no receive filters configured by the host and typically the host does not work in promiscuous mode, so it is redundant to calculate the hash and trigger the RSS queue for packets that should be dropped.

netkvm: filter RX packets as early as possible

---

NetKVM/Common/ParaNdis-RX.h
NetKVM/Common/ParaNdis_Common.cpp
NetKVM/Common/ParaNdis_RX.cpp
NetKVM/Common/ndis56common.h
NetKVM/netkvm-base.txt
NetKVM/wlh/ParaNdis6_Oid.cpp

Implemented a workaround for rx packet loss encountered with TCP_NODELAY. By default, this feature is turned off to minimize the impact on CPU performance and network bandwidth.
To activate the feature, go to the network card properties and set the MinRxBufferPercent to a value above 0. A good starting point is to set MinRxBufferPercent to 25% and then monitor for any packet loss. If packet loss continues, incrementally adjust the value to 50%, then 75%, and if necessary, up to the maximum of 100%.
In extreme cases, it may be required to not only adjust the  MinRxBufferPercent but also to increase the number of queues and the size of each queue (queue_size).
It is important to note that this feature is only applicable to rx packet loss.
For more details, see [this …

[netkvm] add a workaround for rx packet loss

---

viosock/sys/Device.c
viosock/sys/Loopback.c
viosock/sys/Socket.c
viosock/sys/viosock.h

The Socket driver stores socket-related data in memory associated with file objects representing the sockets. It uses `WdfObjectReference/WdfObjectDereference` to track ownership and protect sockets being in use from deletion. However, these routines do not affect reference count of the underlying `FILE_OBJECT` structures (served by Object Manager) -- they work only with the reference count of the WDF object wrapped around the `FILE_OBJECT` structure. Thus, when the underlying `FILE_OBJECT` is deleted, `WdfObjectReference` does not protect the socket context from deallocation.
This commit fixes this issue by introducing `VioSockReference` and `VioSockDereference` which also work with reference count of the wrapped `FILE_OBJECT` structures. Also, `VioSockClose` is replaced with …

Viosock: Fix Socket Reference Management

---

viosock/sys/Rx.c
viosock/sys/Socket.c

When an other end (peer) of the socket reports a shutdown, the `recv` request queue is not processed. This means that some recv calls may get stuck forever. This pull request changes the behavior -- when a shutdown from its peer is received, the recv queue gets processed and all requests that would get stuck are completed with `STATUS_SUCCESS` (which usually ends in receiving zero bytes).
This should fix #1020. I tested with
- client in WIndows VM, server on the host,
- - both client and server within the same Windows VM.

Viosock: Take Care of Recv Requests Stucks After Socket Shutdown

---

VirtIO/WDF/Callbacks.c
VirtIO/WDF/VirtIOWdf.c
VirtIO/WDF/VirtIOWdf.h

Solves: https://issues.redhat.com/browse/RHEL-23315
There is unused code in the WDF library. Cleaning as part of the effort to remove pre-Win10 code from the code base.

[virtio] RHEL-23315: Remove legacy DMA code in the WDF library

---

viogpu/common/baseobj.cpp
viogpu/common/bitops.cpp
viogpu/common/helper.h
viogpu/common/viogpu.h
viogpu/common/viogpu_idr.cpp
viogpu/common/viogpu_idr.h
viogpu/common/viogpu_pci.cpp
viogpu/common/viogpu_pci.h
viogpu/common/viogpu_queue.h
viogpu/viogpudo/viogpudo.h

Currently there are several includes that cause recursive including - it still works because of include guards but it's not good idea for this to happen in first place and sometimes it can cause quite puzzling errors.
Some examples:
* helper.h -> viogpu_pci.h -> helper.h
* helper.h -> viogpu_idr.h -> helper.h

viogpu: Fix recursive includes

---

Tools/Driver.Common.props

HLK for Server 2025 fail INF Verification with the error:
The syntax 'DIRID 13 (CopyFiles)' was introduced in OS version 10.0.16299, but DDInstall sections utilizing the syntax will install on earlier OS versions. Those DDInstall sections should be restricted to only install on 10.0.16299 or higher using a TargetOSVersion decoration.
As Windows 10 before build 16299 is EOL and we don't support it. This is ok, to have DIRID 13 in Windows 10 INF without TargetOSVersion decoration.
Resolve: https://issues.redhat.com/browse/RHEL-1214

Set TargetOSVersion in INF for Windows 11

---

viosock/wsk/wsk-utils.c

This member does not exist on 32-bit versions of Windows. Although such platforms are probably no longer supported, it would be nice to ease the life of those of the community that would need to compile the drivers for these platforms (especially when such change is very simple).
This change should not be dependent on #1066.

WSK: Do Not Access the Flags Parameter in send/recv Requests

---

NetKVM/CoInstaller/NetKVMCo.h

https://issues.redhat.com/browse/RHEL-28542
Due to prototype mismatch there is exception on application exit and wrong return value of the application (x86 only)

netkvmco: fix command handler prototype

---

viosock/viosock-wsk-test/test-messages.c
viosock/viosock-wsk-test/test-messages.h
viosock/viosock-wsk-test/viosockwsk-test.c
viosock/wsk/provider.c
viosock/wsk/socket.c
viosock/wsk/wsk-completion.c
viosock/wsk/wsk-completion.h

This PR implements more advanced calls for the WSK interface:
- `WskSocketConnect` (`WskSocket` + `WskBind` + `WskConnect` in one call),
- `WskConnectEx` (`WskConnect` + `WskSend`),
- `WskSendEx` (the same as `WskSend` for our socket case),
- `WskReceiveEx` (the same as `WskReceive` for our socket case).
The test driver has been updated to test also these calls.
**NOTE:** WSK callbacks (namely the accept and receive ones) are still not implemented since their implementation requires modification of the Socket driver whereas the current goal was to implement the WSK interface without any need to modify the Socket driver (apart from fixing various bugs).

Viosock: Implement Advanced Calls for the WSK Interface

---

NetKVM/Common/ParaNdis_TX.cpp

https://issues.redhat.com/browse/RHEL-24992
Memory leak of CNB::m_ExtraNBStorage happens if the packet os overfragmented but we do not succeed to
allocate extra pages.

netkvm: fix memory leak in TX overfragmenting flow

---

viostor/virtio_stor.c

Signed-off-by: Zhang JianMing zhangjianming.zjm@alibaba-inc.com
for the problem description
please visit #1095

[viostor] fix incorrect IO boundary handling in RhelScsiVerify

---

vioscsi/helper.c
vioscsi/vioscsi.c
vioscsi/vioscsi.h

The two patches handle the disk removal in vioscsi driver. The details is the following,
vioscsi: Process PnP actions for the adapter
When the vioscsi device is deleted on the host side, the driver
should handle the removal I/O properly. Any new SCSI Request
Blocks are completed with SRB_STATUS_NO_DEVICE.
vioscsi: Implement HwUnitControl routine
If multiple LUNs exist in the same storage controler, the
HwUnitControl routine needs to be implemented. This routine
handles operations occurring on LUNs.
When the disk is deleted on the host, the HwUnitControl
routine completes the pending I/Os for the deleted disk.

Handle disk removal in vioscsi

---

Tools/debug/CollectSystemInfo.ps1
Tools/debug/README.md

Add an interruption handler. When the script is not finished running, the generated file name could be marked with the
ongoing process, such as Collecting_Status.txt. and it would be delete after completion. In this way, when the script is waiting to be interrupted, it will be clearer to the userwhich directory was interrupted.
Solves: https://issues.redhat.com/browse/RHEL-50169
Signed-off-by: Dehan Meng <demeng@redhat.com>

[CI-NO-BUILD] Add interruption handler to CollectSystemInfo

---

Tools/debug/CollectSystemInfo.ps1
Tools/debug/README.md

1. Input parameters that are missing, no mechanism for handling
abnormal input, for now, if user type `.\CollectSystemInfo.ps1 -?
(-help, --help)` or `.\CollectSystemInfo.ps1 noniput` , script
always runs without any warning output to the users.
It's not what we expected.
2. If user operate 'ctrl+c' or exit powershell to break the
script-running, the Collecting_Status.txt would be opened and
cause the folder couldn't be removed/cleaned.
Solves: https://issues.redhat.com/browse/RHEL-50330
Solves: https://issues.redhat.com/browse/RHEL-50169
Signed-off-by: Dehan Meng <demeng@redhat.com>

[CI-NO-BUILD] Add 'input validation' to CollectSystemInfo and hot-fix for 'interruption handler'

---

Tools/debug/CollectSystemInfo.ps1

After running script with param 'IncludeSensitiveData', Only the Minidump directory was copied, the dmp file wasn't copied
Solves: https://issues.redhat.com/browse/RHEL-52479
Signed-off-by: Dehan Meng <demeng@redhat.com>

[CI-NO-BUILD] Fix dmp file missing issue

---

Tools/debug/CollectSystemInfo.ps1

'.\CollectSystemInfo.ps1 wrongtype' without '-' still is a common input errors.  Previously, only the ones starting with '-' were filtered.
Solves: https://issues.redhat.com/browse/RHEL-50330
Signed-off-by: Dehan Meng <demeng@redhat.com>

[CI-NO-BUILD] Hot-fix for RHEL50330: Add another situation

---

Tools/debug/CollectSystemInfo.ps1
Tools/debug/README.md

Splite original summary folder to Log and Dump folders for data classification.
And solve a problem that archive big file encounter failure.
Solves: https://issues.redhat.com/browse/RHEL-52721
Signed-off-by: Dehan Meng demeng@redhat.com

[CI-NO-BUILD] Classify original folders and solve a failure

---

viosock/sys/Socket.c

This PR fixes several issues:
- `WSAEventSelect` should not erase previously recorded network events. Rather, it should set the newly associated event object to signaled state if such events are currently recorded.
- `WSAEnumNetworkEvents` must not disassociate the event object with the socket. Its purpose is just to erase the recorded events (after copying them to the user) and reset the event object.
- The `ObReferenceObjectByHandle` function used to translate event object handle to pointer increases object's reference count. This was not reverted in some cases.

Viosock: Fix Issues With WSAEventSelect and WSAEnumNetworkEvents

---

viogpu/viogpusc/Service.cpp
viogpu/viogpusc/utils.cpp

Remove flag SERVICE_INTERACTIVE_PROCESS to run viogpu service as a noninteractive service.
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/718

viogpusc: Run viogpu service as a noninteractive service

---

VirtIO/linux/virtio_config.h
viostor/virtio_stor.c

VIRTIO_F_ORDER_PLATFORM may be required for devices implemented in hardware.
However when adding buffers in vring KeMemoryBarrier is used which prevents both the compiler and the processor from moving operations across the barrier. So just add this feature in guest_feature.

virtio: add VIRTIO_F_ORDER_PLATFORM feature

---

vioinput/sys/vioinput.inx

https://issues.redhat.com/browse/RHEL-58183
Set DMAR compatibility level to 2 (when driver verifier enabled)

vioinput: add DMAR Compatibility to the INF file

---

fwcfg64/fwcfg.inf

https://issues.redhat.com/browse/RHEL-58378
The driver provides physical memory addresses to the device but the QEMU implementation uses DMAR-incompatible access to the memory.

fwcfg: disable DMAR in the INF file

---

vioserial/sys/vioser.inx

https://issues.redhat.com/browse/RHEL-58379
Enable DMAR when driver verifier is enabled.

vioser: add DMAR compatibility support to the INF

---

viostor/virtio_stor.c

according to the definitions of NumberOfPhysicalBreaks and MaximumTransferLength in the Microsoft documentation, as well as the calculation methods provided in commit cfbf9345 for these two variables, in a single io, the number of segments  will not exceed seg_max, and the total size of the io will not exceed seg_max*size_max. therefore, when building io, dirver can split any sgement larger than size_max into smaller requests.
fix https://github.com/virtio-win/kvm-guest-drivers-windows/pull/753/commits

viostor: adapt to size_max

---

NetKVM/Common/ParaNdis_Common.cpp

NetKVM: ack VIRTIO_F_ORDER_PLATFORM
According to commit 48aeb261, add VIRTIO_F_ORDER_PLATFORM to NetKVM.

NetKVM: ack VIRTIO_F_ORDER_PLATFORM

---

viostor/viostor.inx

https://issues.redhat.com/browse/RHEL-58679
Enable DMAR if driver verifier enabled.

viostor: add DMAR support to the INF

---

vioscsi/vioscsi.inx

https://issues.redhat.com/browse/RHEL-58680
Enable DMAR if driver verifier enabled

vioscsi: add DMAR support to the INF

---

viosock/wsk/provider.c

The annotation was accidentally left within the `VioWskSocket` function code during its implementation. SDV complains about it so let's place it right again.

WSK: Correctly move the annotation to the function

---

pvpanic/pvpanic/pvpanic-pci.inf

This is a follow-up to d27499191cd9 fixing the `pvpanic-pci.inf` as well. Discovered by my colleague Konstantin Vlasov.

PVPanic: Fixed pvpanic-pci.inf to pass validation

---

vioscsi/helper.c

Related issues:
#756
#623
#907
...
[likely others]
Regression was introduced in #684 between https://github.com/virtio-win/kvm-guest-drivers-windows/commit/7dc052d55057c2a4dc2f64639d2f5ad6de34c4af and https://github.com/virtio-win/kvm-guest-drivers-windows/commit/fdf56ddfb44028b5295d2bdf20a30f5d90b2f13e.
Specifically due to commits https://github.com/virtio-win/kvm-guest-drivers-windows/commit/f1338bb7edd712bb9c3cf9c9b122e60a3f518408 and https://github.com/virtio-win/kvm-guest-drivers-windows/commit/fdf56ddfb44028b5295d2bdf20a30f5d90b2f13e (considered together).
~~Prior to the regression, we did not issue `virtqueue_notify()` ~~outside~~ inside spinlock. This behaviour has been restored.~~
Prior to the regression, we issued `virtqueue_kick_prepare()` inside spinlock. This behaviour has …

[vioscsi] Fix SendSRB notify regression

---

vioscsi/vioscsi.c

Corrects:
1. A reference to a ghost routine for HW_PASSIVE_INITIALIZE_ROUTINE
2. Some missing braces in VioScsiInterrupt()

[vioscsi] DPC Fixes

---

VirtIO/osdep.h

The `VirtIO\osdep.h` header file defines `ENOSPC` as 1. On Windows this equates to `ERROR_INVALID_FUNCTION`.
This commit redefines `ENOSPC` to use the more typical Linux definition of 28.

[VirtIO] Redefine ENOSPC to common Linux errno

---

VirtIO/VirtIORing-Packed.c
VirtIO/VirtIORing.c
VirtIO/virtio_ring.h
vioscsi/helper.c
vioscsi/helper.h

The `virtqueue_add_buf()` routine will return 0 on `SUCCESS` or otherwise a negative number, usually -28 (`ENOSPC`), i.e no space for buffer. An inline comment is added for edification. Refactored `virtqueue_add_buf()` handling to only process the SRB if `virtqueue_add_buf()` returns `SUCCESS`. Presently, other positive return codes would be processed.
Variable renames:
`res` to `add_buffer_req_status`
`index` to `vq_req_idx`
`MessageID` to `MessageId`
-- Also cleaned up variable init table
New definitions:
`VQ_ADD_BUFFER_SUCCESS` is defined in `vioscsi\helper.h` header file.
-- Used to initialize `add_buffer_req_status` variable. (Credit: @JonKohler)
To ensure valid data is reported we also move the trace event on failure to above the call to `CompleteRequest()` and wrap the line for …

[vioscsi] SendSRB minor refactor

---

viogpu/viogpusc/Session.cpp
viogpu/viogpusc/Session.h
viogpu/viogpusc/SessionMgr.cpp
viogpu/viogpusc/SessionMgr.h

When the user stops the viogpusc service either through SCM or console command line, a timeout error is thrown out as the following,
From the console,
The service did not respond to the start or control request in a timely fashion.
From SCM
A timeout was reached while waiting for a transaction response from the viogpusc service.
This error is due to the incomplete initialization of the Session creating viogpuap process. This initialization is blocked until the process is terminated. When SCM or console command tries to stop the service, it always fails because the Session is waiting for the process to be terminated. Actually, the process is waiting for the service to trigger an event to terminate itself. This is a dead loop.
To fix this issue, the Session initialization should be …

viogpusc: Fix the timeout issue when stopping viogpusc service

---

vioscsi/vioscsi.inx

https://issues.redhat.com/browse/RHEL-62318
https://issues.redhat.com/browse/RHEL-58680
Disable DMAR for storage drivers for now.

vioscsi: disable DMAR in the iNF file

---

vioscsi/trace.h
vioscsi/utils.c

Includes:
a) New RUN_UNCHECKED and RUN_MIN_CHECKED definitions for compilation conditional tracing
b) DBG definition fix (remove superfluous "define")
c) Use keywords for WPP FLAGS
d) New INLINE function WPP definitions
e) WPP Optimisation
f) ETW Prettification
g) Suggestion to cull code for InitializeDebugPrints() when EVENT_TRACING

NO-SDV [vioscsi] Tracing improvements

---

vioscsi/vioscsi.c

Fixes SDV defects in `vioscsi.c`:
a) `HwStorPortProhibitedDDIs` _Must-Fix_ defect in `VioScsiInterrupt()` IRQL for trace
b) `NullCheck` defect in `CompleteRequest()` OpCode for trace

[vioscsi] Fix SDV defects

---

viostor/virtio_stor_hw_helper.c

Backports fixes and improvements from vioscsi PRs #1150 and #1162
virtqueue struct vq was also removed in favour of adaptExt->vq[QueueNumber], which results in a minor performance increase.

[viostor] Backport vioscsi SendSRB fixes and improvements

---

viostor/virtio_stor_hw_helper.c

This fix prevents viostor from reporting requests with MessageNumber of zero as failed even in case they succeed.

Viostor: Do Not ReportEerror When a Request Actually Succeeds

---

vioscsi/helper.c
vioscsi/helper.h
vioscsi/vioscsi.c

Spinlocks are now primarily of the `DpcLock` type, without which the driver will not properly operate. Fallback to an `InterruptLock` type spinlock is limited, perhaps even cosmetic.
This commit removes the `VioScsiVQLock()` and `VioScsiVQUnlock()` wrapper routines to use the native functions instead, i.e. `StorPortAcquireSpinLock()` and `StorPortReleaseSpinLock()`. `VioScsiVQLock()` contained a superfluous MSI-X and `QueueNumber` check and `VioScsiVQUnlock()` did not release non-`DpcLock` type spinlocks. Removing the wrapper routines also resolves these two issues.
Refactoring includes:
* Renaming of `ProcessQueue()` to `ProcessBuffer()`. Whilst technically more accurate, this also provides space for a new `ProcessQueue()` routine, via which the `HW_MESSAGE_SIGNALLED_INTERRUPT_ROUTINE` …

NO-SDV [vioscsi] Reduce spinlock management complexity

---

NetKVM/netkvm-base.txt

https://issues.redhat.com/browse/RHEL-1215
Enable DMAR if driver verifier is enabled

netkvm: declare DMAR compatibility in the INF file

---

Tools/trace/Readme.txt

Correct order of parameters in call of ParseTrace.bat

[CI-NO-BUILD] RHEL-67132: trace: fix readme file

---

build/signAll.bat

1. Use the Germanium EWDK Build Lab environment to sign Win11 drivers.
We currently use the Cobalt EWDK to sign both Win10 and Win11 drivers.

[build] Use Germanium EWDK to sign Win11 drivers

---

build/SetVsEnv.bat

1. Enforce echo off after calling `SetupBuildEnv.cmd`, which will otherwise spill noise into the build log.
If data amongst this noise is required, best to report it specifically.
3. Provide some extra EWDK details when `EnterpriseWDK=True`.
Here we include the `BuildLab`, VS year and dev CLI version as well as the `Version_Number` (EWDK Build Number).

[build] Extend SetVsEnv.bat

---

build/makeLegacyDVLs.bat
vioscsi/buildAll.bat
vioscsi/vioscsi.vcxproj

a) Updates the _CustomBuildStep Command_ to conditionally copy COMPAT and Win10 DVL files. This permits COMPAT DVLs with Checksums and Win10 SDV DVLs to be copied if available.
b) Enables Win10_SDV for local buildAll.bat script.

[vioscsi] Conditionally manage DVL copying

---

viostor/buildAll.bat
viostor/viostor.vcxproj

1. Refactors the _CustomBuildStep Command_ to manage DVL file creation. We now create DVL files in the _Project_ (driver) folder with version numbers in the file name for DVL files created with legacy EWDKs, and with the _"latest"_ label for current EWDKs. These files are then copied to the relevant `.\Install` folders and renamed for extant WHCP submission operations. Makes use of the new `build\makeLegacyDVLs.bat` script (from PR [#1210](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1210)), which now creates all legacy DVL files. Logging is also enabled to provide feedback when read at the tail of `root\buildAll.bat`. Please see PR [#1212](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1212) for details on those changes.
2. Enables `Win10_SDV` for local …

[viostor] Refactored legacy DVL creation

---

NetKVM/NetKVM-VS2015.vcxproj
NetKVM/buildAll.bat

1. Refactors the _CustomBuildStep Command_ to manage DVL file creation. We now create DVL files in the _Project_ (driver) folder with version numbers in the file name for DVL files created with legacy EWDKs, and with the _"latest"_ label for current EWDKs. These files are then copied to the relevant `.\Install` folders and renamed for extant WHCP submission operations. Makes use of the new `build\makeLegacyDVLs.bat` script (from PR [#1210](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1210)), which now creates all legacy DVL files. Logging is also enabled to provide feedback when read at the tail of `root\buildAll.bat`. Please see PR [#1212](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1212) for details on those changes.
2. Enables `Win10_SDV` for local …

[NetKVM] Refactored legacy DVL creation

---

build/dvl1903.bat

1. Deletes `build\dvl1903.bat` script obsoleted by PRs [#1210](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1210), [#1240](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1240) and [#1241](https://github.com/virtio-win/kvm-guest-drivers-windows/pull/1241).

[build] Delete obsolete dvl1903.bat script

---

build/build.bat
buildAll.bat

1. Fixed various syntax issues, including an unquoted variable in conditional test (Debug or Release log file name), superfluous backslashes, spaces between errorlevel tests and tested functions, MSBuild syntax consolidation, prefixing FOR do commands with @, etc.
2. Unwrapped nested IF statements to ensure no jumping out of loops or other unexpected behaviours.
3. Updated usage, including Win11 target and explanation regarding analysis builds (build.bat only).
4. Added analysis build specific variables CODEQL_FAILED and SDV_FAILED to init area (build.bat only).
5. Refactored fail code, removing return failure detection in favour of in-line failure detection.
6. Updated labels to use snake style notation.
7. Refactored end of build_arch function to avoide "goto :eof" and instead use …

[build] Basic fixes and extentions to build scripting

---

build/build.bat
build/prebuild_x86_libs.bat

1. Pre-builds `x86` `viosock` libraries when building `virtio-win.sln` or `viosock.sln` for `amd64` in the circumstances the required `x86` libraries do not already exist.

[build] Pre-build x86 viosock libraries as needed

---

NetKVM/Common/ParaNdis_Common.cpp

Jira link: https://issues.redhat.com/browse/RHEL-75532 Lazy allocation thread must be stopped before resetting virtio device.

RHEL-40693:netkvm: Stop lazy alloc thread on reboot

---

buildAll.bat

1. Refactors body into subroutine for creation of `inf2cat` system drivers
2. Transpose arguments to named variables
3. Use negative `ERRORLEVEL` check to catch all but `SUCCESS`
4. Prepare for colour prints to `stdout`
5. Remove `goto :eof :: never hit` placeholder

[CI-NO-BUILD] [build] Refactor build for inf2cat system drivers

---

buildAll.bat

1. Refactor to ensure any pre-existing DVL files are not clobbered.
2. Expand `FOR` loop

[CI-NO-BUILD] [build] Preserve existing WIN10_RS1 (1607) COMPAT DVLs

---

viostor/virtio_stor_hw_helper.c

1. Refactored to only return `TRUE` when `add_buffer_req_status == VQ_ADD_BUFFER_SUCCESS`.
2. Pro-actively refactors calls to `InterlockedIncrement()` back to the
`add_buffer_req_status == VQ_ADD_BUFFER_SUCCESS` path.
Impacts: `RhelDoFlush()`, `RhelDoReadWrite()`, `RhelDoUnMap()` and `RhelGetSerialNumber()`.
Regression introduced with PR #1174 (379f291).
Will likely resolve issue #1204 (RHEL-70446)
Unlikely to resolve issue #907.
My bad... 8^d

RHEL-70446: [viostor] Fix returning SUCCESS when really -ENOSPC (regression)

---

NetKVM/Common/ParaNdis_Common.cpp

Fix an array out-of-bounds in function ParaNdis_OnPnPEvent().

[NetKVM] netkvm: fix an array out-of-bounds error

---

NetKVM/Common/ParaNdis-Util.h

Jira link: https://issues.redhat.com/browse/RHEL-22354
In the investigation with CNBL history we can see that the decision based on read of m_DpcWaiting was not correct. The value reads as 1 but the m_AuditState.LastTxProcess show the timestamp in past (using perf counter timestamps), 30 micros ago. Making read of ref counter interlocked.

[RHEL-22354] potential fix for stuck packet

---

viogpu/common/viogpu_queue.cpp
viogpu/common/viogpu_queue.h
viogpu/viogpudo/viogpudo.cpp

I occasionally saw viogpu crashes the whole system because of AllocCmd()
returning NULL. viogpu allocates buffers according to the queue size and
while it works fine in most cases, the specification says:
> Once the ring is full of driver descriptors, the driver stops sending
> new requests and waits for the device to start processing descriptors
> and to write out some used descriptors before making new driver
> descriptors available.
While waiting for the device in such a scenario, the driver will need to
hold buffers more than the queue size.
Allocate a buffer if we need more than the queue size, but free it once
it becomes unnecessary so that we will not keep unbound amount of memory
indefinitely.

viogpu: Allocate more buffers than the queue capacity

---

NetKVM/Common/DebugData.h
NetKVM/Common/ParaNdis-TX.h
NetKVM/Common/ParaNdis-Util.h
NetKVM/Common/ParaNdis-VirtQueue.h
NetKVM/Common/ParaNdis_Debug.cpp
NetKVM/Common/ParaNdis_DebugHistory.h
NetKVM/Common/ParaNdis_TX.cpp
NetKVM/Common/ParaNdis_VirtQueue.cpp
NetKVM/Common/ndis56common.h
NetKVM/wlh/ParaNdis6_Driver.cpp

This PR is a collection of minor changes and instrumentations taken out from development branch related to  support for NBL chains completion for easier review

[RHEL-22354] Preparation PR for NBL chain series

---

vioscsi/vioscsi.c

We have discovered a problem introduced with 35331dad1 where a guest would hang on LUN removal if there are pending IO requests in the processing_srbs queue. 
The fix is pretty trivial. 
The stuck PNP thread looks like this:
```Process                   Thread                       CID       UserTime KernelTime ContextSwitches Wait Reason    Time State
System (ffffae0403a93040) ffffae0409f9d300 (E|K|W|R|V) 4.1500           0    59s.328            4773 Executive   58s.750 Running on processor 3
Irp List:
IRP              File Driver
ffffae040ab4c460      vioscsi
Priority:
Current Base Decrement ForegroundBoost IO Page
13      12   0         0               0  5
0 (Inline)         ---------------- vioscsi!SrbGetTargetId                    F:\ewdk\2022\Program Files\Windows …
```

vioscsi: fix infinite loop on surprise removal if srb_list is not empty

---

vioscsi/vioscsi.c

ScsiQuerySupportedControlTypes should be ScsiQuerySupportedUnitControlTypes

[vioscsi]: fix warning as error ScsiQuerySupportedControlTypes

---

Tools/debug/CollectSystemInfo.ps1

RHEL-50142: Add IO limits to the Windows Guest debugging tools [CI-NO-BUILD]

---

viogpu/viogpudo/viogpudo.inx

Resolve: https://github.com/virtio-win/kvm-guest-drivers-windows/issues/1335

RHEL-99518: Add generic HWID (PCI\VEN_1AF4&DEV_1050) to viogpudo INF

---

viosock/tcp-bridge/bridge.cpp

According to https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-recv If the connection has been gracefully closed, the return value is zero. This means that connection is closed and service can stop bridging actions.

RHEL-101554: [viosock/tcp-bridge] Exit threads when recv read 0 bytes

---

viogpu/common/edid.cpp
viogpu/common/edid.h
viogpu/viogpudo/viogpudo.cpp

These three commits are supposed to fix some flaws in processing EDID Established timings I, II, and III. 
1. Added some extra logging to have better understanding what we get from EDID
2. Established timings I, II: the code was simply missing all checks to report all the resolutions
3. Established timings III: the structure was incorrectly defined as the result the code started processing resolutions from the 5th byte while 5th byte represents revision. 
4. Standard timings: the resolutions incorrectly reported by the adapter as the code uses RefreshRate instead of ImageAspectRatio. 
More details on item 3:
With some extra logging we can see that we get resolutions that are actually not expected:
```00000045	viogpudo.sys	4	800	1	45	08\21\2025-15:12:51:811	 VioGpuAdapter::AddEdidModes …
```

viogpu fixes processing edid

---

viomem/sys/trace.h

Remove code in viomem related to unsupported Windows versions.

RHEL-108856: [viomem] Remove code related to unsupported Windows versions

---

vioscsi/helper.c
vioscsi/helper.h
vioscsi/vioscsi.c
viostor/virtio_stor.c
viostor/virtio_stor_hw_helper.c

the motivation for this sequence is to synchronise the upstream with our downstream code-base. We reverted a couple of previously merged commutes and QE run very intensive functional and WHQL testing on theses changes. In addition to that there are two similar changes for viostor and vioscsi drivers to reset the transfer length to 0 for SRBs completed during bus reset processing. We found that out without this change the system reports the problem incorrectly, saying that it was a MEMORY MANAGER CRC problem (happened during page-in operation).
Thanks,
Vadim.

sync with the latest downstream viostor and vioscsi related changes 
